### ISSUE TITLE
Metrics page + data visualization

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#114]
### What does a metrics page look like?
- What questions need to be answered?
- How to visualize what has changed with a bunch of contracts over a period of time
### What does the weekly report look like?
- Spreadsheet?
- Graphs? 
- Ponies?

**Comment by bsmithgall** [comment]
@hamhands it would be great if you could attach wireframes here when you have them

**Comment by hamhands** [comment]
@bsmithgall :+1: coming soon

**Comment by msknee** [comment]
Update: scheduled call with @rileystewart for 11:30AM EST, Wednesday 7/22 to talk about data needs.

**Comment by hamhands** [comment]
Thanks @shellicious!

**Comment by bsmithgall** [comment]
Can you post the results of this here?

**Comment by msknee** [comment]
Results:

![screen shot 2015-07-22 at 1 26 01 pm](https://cloud.githubusercontent.com/assets/1178390/8836364/3e548e5c-3075-11e5-8d4e-695600ef92ad.png)

Notes from chatting with @rileystewart:
- County agent data is not useful (they change)
- Changes in the # of days option:
  -- useful if she can make it into a bar chart or scatter graph
- Count + list option:
  -- combines 2 things she can figure out herself if there’s a counter
- Average # of days a step takes, by year
  -- Would like to see monthly option
- Confirmed need to make sure editing flows and steps in the Admin works for OMB
  -- A bids under 30k, though rare, are city only bids that skip city EORC and county MWBDE steps

Link to doc we used for the sorting exercise: https://docs.google.com/drawings/d/1yKWGLxfJKJIrAakdMsYrnwQyn-qTUExWW06kCeZ6_do/edit

**Comment by hamhands** [comment]
First stab :hocho: at metrics page:
![conductor-metrics-01](https://cloud.githubusercontent.com/assets/3640800/8920841/56069d1c-3483-11e5-894f-d92fc8a6f00f.png)

**Comment by hamhands** [comment]
@bsmithgall @shellicious take a look and let me know what yinz think.

I played around with a few different ways to organize the info (including a card interface, with contract details on the back of a given card), but settled on the above for simplicity of interface. Riley could print a view of this up fairly easily, I think.

One thought I had, and I know it's not possible yet, is if each of the boxes on the top section could link directly to their respective filtered view of the contracts. "45 contracts expire in the next 4 months" could link to contracts that expire in the next 80 business days, etc. Let me know how dumb that is @bsmithgall.

**Comment by hamhands** [comment]
### Feedback from 8/10 meeting with Riley
- Love the part of average business days at given step
- Missing: count of how many contracts in each step (e.g. 5 in eorc, 3 in dept review, etc.)
- Less important/don't need: renewing less, in bid process, not renewing or bidding out
  - total being bid out not as important as _where_ they are in the bid process
  - renewing less important, but still useful
- Not into histogram, prefer data grouped into buckets
  - < 7 days, 7-14 days, more than 14 days, etc., maybe in pie charts or stacked bar graph
- Export options
  - Filtering by date might be helpful, but bulk export is fine too so long as date column is included

**Comment by msknee** [comment]
Milestones:
- [x] Clean historical data (in progress by @hamhands), covered by #159 
- [ ] MVP: Generate bar graphs (average days per step, and days per step grouped into buckets) based on historical data
- [x] MVP: download button for CSV of historical data
- [ ] Iteration 2: another download button for CSV of "present" Conductor data (data that is not historical)
- [ ] Iteration 2: Generate bar graphs based on present and historical data
- [ ] Iteration 3: Generate summary panel (the section with the large numbers + detail view of contracts referenced) for present data

**Comment by msknee** [comment]
@bsmithgall @hamhands your thoughts welcome on order of operations / additional tasks for above ^^

**Comment by hamhands** [comment]
Update:

Got charts + a stacked bar extension installed and initialized a tester graph:
<img width="1116" alt="screen shot 2015-08-21 at 3 52 08 pm" src="https://cloud.githubusercontent.com/assets/3640800/9420686/33ecc44c-481d-11e5-892c-a407f0a3187f.png">

Next up: load actual data
Next next up: add year buttons, onClick events, etc
Next next next up: rejoice.

**Comment by bsmithgall** [comment]
What's on the Y-Axis?

**Comment by hamhands** [comment]
@bsmithgall it's just random numbers at this point

**Comment by msknee** [comment]
:+1: to an Almost Real Graph

**Comment by hamhands** [comment]
<img width="1091" alt="screen shot 2015-08-23 at 9 43 11 pm" src="https://cloud.githubusercontent.com/assets/3640800/9431467/08e28448-49e0-11e5-828f-e386e9fa1d62.png">

**Comment by bsmithgall** [comment]
Hm, that actually doesn't look all that helpful.

I think small multiples might be a better pattern here.

**Comment by hamhands** [comment]
Yeah, the stacked bars don't work that well :unamused:

**Comment by bsmithgall** [comment]
Also todo: compile a list of domain questions.

**Comment by bsmithgall** [comment]
We're going to work towards an MVP of a simple number-of-days chart.

**Comment by bsmithgall** [comment]
![screen shot 2015-10-12 at 4 03 44 pm](https://cloud.githubusercontent.com/assets/1957344/10437414/dd9076aa-70fa-11e5-976e-12733a71a56e.png)
![screen shot 2015-10-12 at 4 03 36 pm](https://cloud.githubusercontent.com/assets/1957344/10437415/dd943308-70fa-11e5-8e98-aa306f811a2e.png)

**Comment by bsmithgall** [comment]
Still todo: get everything to match the flow's order.

**Comment by msknee** [comment]
Above screenshots, merged:

![metricspage_101315](https://cloud.githubusercontent.com/assets/1178390/10456456/74dc9978-718f-11e5-8124-8c395eee5d60.png)
