### ISSUE TITLE
Beacon Domain

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#117]
What are we doing with this?

**Comment by bsmithgall** [comment]
@shellicious can we keep track of what's happening with that here?

**Comment by msknee** [comment]
@bsmithgall Yup! Sent request to @laurameixell Monday 7/20, who forwarded it to Sylvia.

**Comment by msknee** [comment]
Heard back from @laurameixell. Sylvia OK'ed it. Next step is talking to Eric and the webteam about getting it done sometime next week (the week of Mon 7/27).

**Comment by msknee** [comment]
Met with @laurameixell and the Webmasters. We'll use a simple beacon.pittsburghpa.gov redirect to the existing heroku URL.

**Comment by bsmithgall** [comment]
Are we closing this then?

**Comment by msknee** [comment]
I'll close it when we get the beacon.pittsburghpa.gov redirect

**Comment by msknee** [comment]
Didn't get the redirect, got buildpgh.com instead!
