### ISSUE TITLE
Beacon Architecture Overhaul

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#118]
Vendor/community facing:
- `/`: Splash/landing page
- `/opportunities`: See lists of opportunities and sign up for updates on individual opportunities. There are also needs for good language when there are no current or upcoming opportunities. @shellicious it would be good to get that when you get a chance.
- `/opportunities/:id`: See an individual opportunity. Post questions to that opportunity. See answers to other questions on that opportunity.
- `/signup`: Sign up for categories
- `/manage`: Manage your subscriptions

City/OMB Facing:
- `/admin/opportunities/pending`: See list of pending opportunities (OMB only) and publish them
- `/admin/opportunities/new`: Submit a new opportunity to OMB
- `/admin/opportunities/:id/edit`: Edit an existing opportunity (publish/unpublish if OMB)
- `/admin/signups`: Small dashboard/view for signed up vendors with download functionality

**Comment by bsmithgall** [comment]
@shellicious for the signups, how should that information be presented? We talked about having an Excel spreadsheet, but other than that were there visual displays that we wanted to show? Graphs/charts? Is that overkill?

**Comment by bsmithgall** [comment]
I'm going to do this in a series of PRs I think. #127 addresses the actual URL structure. I'm going to open one tomorrow for the `pending` page, and then I'm going to do a separate one for the signup page and one last one for the changes to the new/edit form.

**Comment by msknee** [comment]
@bsmithgall: What do you mean by visual displays? Like, how city staff access the emails collected? For that, Excel spreadsheet for now. #lean

**Comment by bsmithgall** [comment]
So then maybe this isn't actually a page for now, just a link in the navbar that you can click and download all of the emails. Do we want to limit who can do this?
