### ISSUE TITLE
Changes to beacon add individual opportunity view

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#119]
#### Overall changes
- [x] More descriptive text boxes
- [x] Clearer titles & text (who is the contact email? what kind of description? what do you mean by title?)
- [x] Document solicitation needs to be either an explicitly PDF or allow word documents. Right now my preference is to favor PDFs over Word documents because they can't be changed as easily once uploaded, but I'm open to hear other opinions (@hamhands @shellicious)
- [x] Allow you to upload multiple files
#### Documents Needed

People find this section confusing (this was not made any better by our not uploading any document types).
- [ ] How are people supposed to know what documents they need to upload?
- [ ] People need to have links to explicit examples when they are looking at these things.
- [x] Title needs to be clearer

**Comment by bsmithgall** [comment]
@hamhands @shellicious Still more in favor of .pdfs only, please lmk what you think.

**Comment by msknee** [comment]
@bsmithgall Slim had an interesting point when he said that this could be used by depts who still have draft versions of RFPs. It would be easier for him to receive doc versions of drafts. Dan at I&P also mentioned his inability to convert docs to PDFs on city computers (??), so I think it's safer to allow both options. 

..this is an opinion weakly held, however.

**Comment by bsmithgall** [comment]
I'm 100% sure you can convert to a pdf on a city computer, but that's fine.
