### ISSUE TITLE
Changes to Beacon Signup Form

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#120]
On signup form:
- Hide "Add Another Category" button until the first button is clicked
- After you add another category, it shouldn't start on "Apparel", it goes back to the "Choose one"

On FAQ:
- Linking to individual insurance certificates/bid bonds/etc.
- Add link to signing up for tax numbers (with state).

**Comment by bsmithgall** [comment]
@shellicious do we have links for the different individual documents? Not sure how to accomplish the bits for the FAQ. If we don't have it right now, it would be better to open a new issue, and merge the code that fixes the signup bits.

**Comment by msknee** [comment]
@bsmithgall we do not. I'll open a new issue.
