### ISSUE TITLE
Contract update view changes

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#121]
#### Definite changes
- [ ] Title of current step should be a question
- [x] Unify tabs
- [x] Actions accessible from all tabs: "Send email", "Extend contract", and "Add note"
- [ ] "Advertise" action from "Advertise" step creates a Beacon post
- [x] Add list of county agents for email drop down
- [x] Add list of department contacts for email drop down
- [x] Expose list of people following a contract
- [x] Cc field for emails
- [x] Send emails to multiple people
#### Larger issues / open questions
- [x] How to switch flows? At the "Received departmental review" step, the contract can be renewed, bid out, or left to expire. Each of these flows is different. How do we address the branching? Have 3 separate buttons that determine the rest of the steps shown?
- [x] A new spec number is assigned by the County if the contract goes out to bid. How to change the spec number when this happens? In the admin, or as an action on a specific step?

**Comment by bsmithgall** [comment]
For the titles of the stages, is it better to just do that, or is it better to build a system to create/manage stages & flows? I think we'll have to do that anyway.

**Comment by bsmithgall** [comment]
Also, 

```
 Add list of county agents for email drop down
 Add list of department contacts for email drop down
```

These need some additional thinking -- where do they come from? How do you add them? Outside of followers, how do we do this association?

**Comment by msknee** [comment]
@bsmithgall There's existing data we can plug in right now, and I imagine a simple interface in the admin where OMB staff with access can use to add or remove county agent names and emails, and add or remove departmental contacts.

Other data sources:
- County agent contact info is posted on the Allegheny County site: http://www.county.allegheny.pa.us/purchasing/staff.aspx 
- Slim has a list of departmental contacts he emails about OMB announcements we can plug in or ask him to add
- The existing contract management spreadsheet has county agents assigned to a majority of the contracts

**Comment by msknee** [comment]
@bsmithgall I'd say the priority is changing the titles so they are questions for now, and then taking a look at stages/flow in the admin as a separate issue.

**Comment by bsmithgall** [comment]
@shellicious they aren't hard coded anywhere, so they have to be changed from the admin itself. The main question is whether or not we want to allow Ed to edit them, for example.

**Comment by bsmithgall** [comment]
Bump. The stuff that's related to flows/stages is all configurable and can be changed. Do we want to allow, for example, Ed to have access to that part of the Admin? If so, I should spend some time on a better way for him to link stages together into flows.

**Comment by msknee** [comment]
@bsmithgall Ed should be allowed to change things, as the primary user of Conductor

**Comment by bsmithgall** [comment]
Right but how? Through the admin? Through something directly in the
conductor interface not currently in the admin?

**Comment by bsmithgall** [comment]
For now, we can help them set things up through the admin. It's a bit wonky and I can't get it to do exactly what I want, but it works.

As for contract metadata itself, it's a really tricky question. I think what we want to do is the following:
1. When a contract is _assigned_ (or whenever work is started on that contract), _clone_ the contract object. Leave the spec number/controller number blank. This will ensure that it doesn't show up in the scout searches.
2. If the contract updates normally, keep it moving as planned.
3. If the contract is _extended_, delete the cloned object and change the expiration date (NOTE: this assumes that extended contracts share spec numbers. I'm pretty sure they do, but it would be good to confirm in the call w/OMB tomorrow).
4. If the contract is renewed, etc. it's going to have a new controller/spec number, so everything goes along normally.
5. Whenever work is finished on a contract (and it isn't just extended), we do what we are doing now -- archive the old contract, expose the new contract, and move the appropriate references over to the new one.

**Comment by bsmithgall** [comment]
This is coming along to some degree. Extensions seem to work reasonably well, and I've ironed out some quite dumb things.

I'm going to have to re-write the search index trigger -- because there is so much adding/deleting/modification, it needs to be tuned a bit more (it should only run when contracts that are visible on scout are added/modified/deleted).

**Comment by bsmithgall** [comment]
I'm not totally sure the right way to expose all of these email contacts given that we are doing a unified tab. Where does all of this information live? How does it get there? This is doubly true for the county agents.

**Comment by bsmithgall** [comment]
Current status:

![autom8](https://cloud.githubusercontent.com/assets/1957344/9105705/09278940-3bcf-11e5-8fac-6dc27ed5f8e9.gif)

**Comment by bsmithgall** [comment]
For user/department/contract:
- [x] New department model 
- [x] Association of users with departments
- [x] Association of contracts with departments
- [x] People to email -- list of everyone who is in the department associated with the contract, list of people following the contract

For county purchasers:
- [x] Add another role -- county purchaser, which has the same level of permissions as staff. County purchasers can be added via the admin.

**Comment by bsmithgall** [comment]
Current status:

![autom8](https://cloud.githubusercontent.com/assets/1957344/9147076/2b3d6cfe-3d17-11e5-8cd9-3b4b0cd61254.gif)

**Comment by bsmithgall** [comment]
Thanks to @wpietri !

If we switch flows, we are going to just revert back to the first stage of the new flow, preserving the action log and presenting it to the user in the interface.

For adding a new stage into a flow, we are going to have to ask OMB what they want to do.

**Comment by bsmithgall** [comment]
Switching flows:

![autom8](https://cloud.githubusercontent.com/assets/1957344/9159940/1adbd4dc-3ee7-11e5-97be-2dff080decee.gif)
