### ISSUE TITLE
Seed Beacon with contracts

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#122]
- [ ] Add pre-qualified contracts from Bidnet: http://www.govbids.com/scripts/PAPG/public/OpenBids/ViewSolicitations.asp
- [x] Add 1 RFP from OMB site: http://apps.pittsburghpa.gov/omb/RFP_Final.pdf

**Comment by bsmithgall** [comment]
Blocked until deploy of production

**Comment by msknee** [comment]
1st public RFP! http://pittsburgh-purchasing.herokuapp.com/beacon/opportunities/1

**Comment by bsmithgall** [comment]
Is this finished?

**Comment by msknee** [comment]
FOR NOW
