### ISSUE TITLE
BUG - Doesn't display properly on IE8

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#124]
SURPRISE!

We need to:
- Follow along here: http://getbootstrap.com/getting-started/#support-ie8-ie9
- Include an [HTML5 Shim](https://github.com/afarkas/html5shiv)
- Include [Respond.js](https://github.com/scottjehl/Respond)

**Comment by hamhands** [comment]
@bsmithgall what are your thoughts on the conditional formatting drop in for htmlshiv? Should it go in the scripts section of layout.html or assets.py?

```
<!--[if lt IE 9]>
    <script src="bower_components/html5shiv/dist/html5shiv.js"></script>
<![endif]-->
```

**Comment by hamhands** [comment]
pittsburgh-purchasing-staging.herokuapp.com still not working on IE8. Stylesheets and JS are still loading, in the right order, so Ima start throwing out random reasons why it might not be working:
1. @import issues (see teh [readme](https://github.com/scottjehl/Respond#support--caveats))
2. [Cross-domain issues](http://pittsburgh-purchasing-staging.herokuapp.com/)? (jk right?)
3. Goblins

@bsmithgall?

**Comment by hamhands** [comment]
*not working: media queries still broken in ie8

**Comment by hamhands** [comment]
cc: @ondrae
