### ISSUE TITLE
Explore Docker

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#13]
Now that [heroku supports docker](https://blog.heroku.com/archives/2015/5/5/introducing_heroku_docker_release_build_deploy_heroku_apps_with_docker) and [heroku dyno pricing is changing](https://blog.heroku.com/archives/2015/5/7/heroku-free-dynos), it might be worthwhile to explore [Docker](https://www.docker.com/) with the eventual goal of making it easy to move the app from heroku to a different platform seamlessly (like AWS for example).

**Comment by bsmithgall** [comment]
Docker development is happening on [this branch](https://github.com/codeforamerica/pittsburgh-purchasing-suite/tree/docker-experimental)

**Comment by bsmithgall** [comment]
A potential issue here -- docker-compose and Heroku don't play all that nicely. Additionally, the heroku-docker plugin is really not all that great: the base images is something like 500mb, which seems to fly pretty far in the face of the "one process per container" Docker methodology. My thinking here is that we should probably stick within the purely blessed-by-heroku development/deployment methodology (e.g. use foreman to achieve development/production environment parity). As we add additional features/need things like caching, Docker will be a good way forward.

I'll continue to maintain the [docker-experimental](branch) as we continue development, but using Docker + Heroku doesn't seem like a great path.

**Comment by bsmithgall** [comment]
Bump. Based on a conversation w/Pittsburgh webteam, this is actually something we want to re-open.

**Comment by msknee** [comment]
wontfixing
