### ISSUE TITLE
Beacon /opportunities list page

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#133]
Tweaks:
- [x] "All Opportunities" in h4 (small, bolded, all caps)
- [x] Change next 2 titles to "Currently accepting proposals" and "Upcoming", and style them as h3 and strong
- [x] Change last title to "Subscribe to selected opportunities" to h4
- [x] Only show subscribe form if there are opportunities available to select, in either list.
- [x] Get rid of the skinny gray line EDIT: line is OK
- [x] Add paragraph underneath explaining what sign up does: "You'll receive email reminders about the opportunities you select. If this is your first time subscribing, we'll ask you for some more information about your business." EDIT: decided against this paragraph due to wordiness.

**Comment by bsmithgall** [comment]
@shellicious are you taking these?

**Comment by msknee** [comment]
@bsmithgall Yes! Do I need to wait for changes you're making?

**Comment by bsmithgall** [comment]
Go for it :+1: i'll fix up eventual merge conflicts on my end
