### ISSUE TITLE
Scout fixes from July user testing

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#145]
- [x] Line items should be associated with specific companies, if there are multiple companies on a contract. This is from Steve's experience when we tested at EMS, searching for CPAPs, and not being able to figure out what company on the Disposable Medical Supplies contract to purchase from. This is somewhat of an edge case.
- [x] IE8 issues, as noted in #124: https://github.com/codeforamerica/pittsburgh-purchasing-suite/issues/124
- [ ] Replace logo image with Scout logo from @shellicious (Shelly will add final version of logo here)

**Comment by bsmithgall** [comment]
- [x] Nobody knows that the title is the contract.

**Comment by hamhands** [comment]
@bsmithgall @shellicious how should we address the last task? Do we need special titles?

**Comment by msknee** [comment]
@hamhands try putting a tiny PDF icon (literally the letters "PDF" or an icon of a document. PDF probs works better) next to the linked text

**Comment by hamhands** [comment]
@shellicious ohhhhh I get it now. Didn't realize the problem was the linking to the PDF.

**Comment by bsmithgall** [comment]
I would even break it out from the title entirely and turn it into a button
underneath (View Contract [pdf icon]).

**Comment by hamhands** [comment]
Breaking the logo task out into its own thing. Will complete once @shellicious finishes it.
