### ISSUE TITLE
Beacon prep for soft launch

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#146]
In preparation for soft launch:
- [x] remove drop down options from the nav bar
- [x] remove "how to bid" section for now

**Comment by bsmithgall** [comment]
This is the left-most drop-down right? I'm going to move it to the logged-in view, as discussed?

**Comment by msknee** [comment]
Yup!

**Comment by bsmithgall** [comment]
+ [x] Fix opportunity add user bug
