### ISSUE TITLE
Beacon email strategy for more vendors to sign up

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#149]
- [x] confirmation email for people who sign up for categories
- [x] confirmation email for people who sign up for specific opportunities

Working doc for emails here: https://docs.google.com/document/d/12wP-POnrG8slJEN3q0-fTnzdBuUHyWuOPPvM3k2MLI8/edit

**Comment by bsmithgall** [comment]
@shellicious The email templates for Beacon are contained in `purchasing/templates/opportunities/emails`. `base.html` contains the actual styles. All of the content should be templated out.

**Comment by bsmithgall** [comment]
IDEA: (thanks @matthewloveless): bi-weekly roundup of all opportunities in the past two weeks.

**Comment by msknee** [comment]
Created a spreadsheet of businesses and orgs to reach out to leading up to official launch on 9/23: https://docs.google.com/spreadsheets/d/1V54Eo-ZDUj_A29Kg3BrMDQex7dAs2wV8q7cKxHdHYS0/edit#gid=0

**Comment by msknee** [comment]
Closing this since this became an email notification issue that is now complete. Opening a new one for emailing vendors on Scout about Beacon
