### ISSUE TITLE
Import and Integrate COSTARs data

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#15]
COSTARs data needs to be imported. This should probably be treated as line item data as per #9

**Comment by bsmithgall** [comment]
On second thought, I think we'll probably treat these as individual contracts to make them come up as individual search results. It's an awkward situation because the expiration is on a per-company level, and expiration date is a top-level contract piece of data.

Here's a possible schema:

**Contract**

| Contract Description | Expiration | Controller Number | Property Key | Property Value |
| --- | --- | --- | --- | --- |
| COSTARS 5 - Pitt Chemical & Sanitary Supply | 2016-01-09 | 48316 | Counties | Allegheny |

**Company**

| Company Name |
| --- |
| Pitt Chemical & Sanitary Supply |

**Line Items** (everything with YES marked on that sheet and a list of the manufacturer)

| Item Name |
| --- |
| Cleaning Supplies and Chemicals |
| Deodorizer/Odor Conteractant |
| Dilution Control Systems |
| Floor Finisher and Remover (supplies and chemicals) |
| Janitorial Paper Products |
| Specialized Floor Cleaning Equipment Rental |
| Algonquin Products |
| BayWest Paper/Dispensers |
| Diversey, Inc. (formerly JohnsonDiversey) |
| Nobles Equipment by Tennant Company |
| Spartan Chemical Company, Inc. |
| Stoko Hand Care |

etc.

**Comment by bsmithgall** [comment]
So the TODO here looks something like:
- [x] Write importer for this (or updated) contract list
- [x] Drop COSTARs contracts from the original CSV

**Comment by bsmithgall** [comment]
Progress:

![screen shot 2015-05-12 at 3 37 39 pm](https://cloud.githubusercontent.com/assets/1957344/7600071/d8fc9c88-f8bc-11e4-9f7c-cd5a8b5d551f.png)

**Comment by bsmithgall** [comment]
Two open questions:
- Should the manufacturers be considered separate line items?
- How should line items be formatted (this is related to #9, #17)?

**Comment by bsmithgall** [comment]
Another open question, how do we feel about grouping everything into one contract? You end up with something like this (which I think I like better):
![screen shot 2015-05-12 at 3 55 21 pm](https://cloud.githubusercontent.com/assets/1957344/7600397/88b66134-f8bf-11e4-96e5-b8b23b176a13.png)

**Comment by bsmithgall** [comment]
Actually, now that I think about this more, they are all different contracts because they are going to have different line items for each one...

**Comment by bsmithgall** [comment]
Yeah, with line items incorporated, I think they should all be considered separate contracts.

![screen shot 2015-05-12 at 4 14 54 pm](https://cloud.githubusercontent.com/assets/1957344/7600654/1660619a-f8c2-11e4-8cb7-ef1840f3bf9e.png)

**Comment by rileystewart** [comment]
Looks good ben. Where are you thinking that manufacturers will go?  They could go under the Line Item side but I think it should have a separate header that says 'manufacturers offered' or something.

also it isn't counties SERVED, it's the county it's located in.  I only put the county if it was local to allegheny or one of the surrounding counties.  Every single vendor on that list has already been screened and serves allegheny county

**Comment by bsmithgall** [comment]
Welcome to Github @rileystewart :tada: :tada: :tada: 

I'll change that, it is pretty straightforward. The way you are describing it, it sounds like they should really be grouped as a contract property. We'll continue to work with layout and formatting as this is a new feature.

**Comment by bsmithgall** [comment]
Ok, new screenshot @rileystewart, we're going to work on the formatting.

![screen shot 2015-05-13 at 5 16 04 pm](https://cloud.githubusercontent.com/assets/1957344/7623788/d77eb3fa-f993-11e4-8aa1-6fdec683ba64.png)

@hamhands @shellicious if you :+1: I'll dump the rest of the COSTARS data off of the current spreadsheet I have and put it into the repo and merge.
