### ISSUE TITLE
New opportunity emails

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#155]
- [x] Content for notification that a new opp is created
- [x] Actual sending of email

**Comment by bsmithgall** [comment]
As a part of this, we should probably include notification emails when someone signs up.

**Comment by msknee** [comment]
@bsmithgall: agree. That's addressed here: https://github.com/codeforamerica/pittsburgh-purchasing-suite/issues/149

**Comment by msknee** [comment]
Draft of content, under the 3rd bolded heading: https://docs.google.com/document/d/12wP-POnrG8slJEN3q0-fTnzdBuUHyWuOPPvM3k2MLI8/edit
