### ISSUE TITLE
Flow chart of work flows ~~~

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#156]
All the Beacon workflows ~~~

**Comment by msknee** [comment]
City staff & OMB workflows for creating, editing, and publishing opportunities: https://docs.google.com/drawings/d/1TCFdlqI94v_M_ekg13NDGG6LHaC-50FxUyEW5u_wEBw/edit

![beacon workflows](https://cloud.githubusercontent.com/assets/1178390/9053232/0ed78182-3a27-11e5-82f3-41e98cbbe777.png)

**Comment by bsmithgall** [comment]
Can we close this @shellicious ?
