### ISSUE TITLE
Spreadsheet clean up

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#159]
Clean up spreadsheet for historical contract in/out times. Metric woo metrics!

**Comment by hamhands** [comment]
### Current plan

Gleaning date and department info from the contract tracking spreadsheet from OMB, producing metrics for historical time spent in each step. This deviates from the original intention of importing all historical contracts, but will produce a baseline by which to compare future improvements.

So...prepare for a table with a bunch of day counts.

**Comment by hamhands** [comment]
### What does "~" mean???

Cases (as confirmed by Ed):
1. This contract went through an alternative process (rebid, renew, closed, piggyback, sole source, etc.)
2. This contract started without OMB's knowledge, thus didn't go through the typical dept review --> to county --> advertise --> etc. flow
3. This contract came about after a previous contract was closed, rejected, or otherwise stopped (item number will likely include a letter, a la 283c)
4. Non-responsive end user, process moves forward
5. This contract was killed "on the vine", meaning that there was no spend on the contract for a given period of time, end user was contacted about closing the contract, and a new contract wasn't pursued after expiration (variation on the first case)

**Comment by hamhands** [comment]
Open question: what to do with ~ when they come before the advertise step. 

Here's my thinking:
- **if a ~ comes up after being advertised**: it likely received no bidders. This tends to be noted somewhere, but in cases that it isn't I think making the assumption that something killed the contract midway through the process is fair and it should be removed from analysis
- **if a ~ comes up before being advertised**: this likely means that the contract was initiated and pursued independently of OMB. It's fairly common for rows to have a date entered for open date, with a ~ for the earlier steps. What to do with these??? Options:
  1. Give all preceding cells the value of the nearest cell with a date
  2. Remove this contract for consideration when calculating pre-advertise period metrics
  3. Add a tag that indicates this contract was independently pursued. This is a variation of option 2.
- Given the above two considerations, is there a case to be made that metrics for each step should be calculated only when a date is present? If we did this it would make the data cleanup process a bit easier and less assumptive, but it would make it harder to compare metrics between steps. If step a has 30 valid begin/end dates and step b has 100, can we really compare the two?

I welcome all thoughts @bsmithgall @shellicious

**Comment by bsmithgall** [comment]
Can we close this @hamhands ?
