### ISSUE TITLE
Prototype of Opportunities Site

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#16]
NOTE this is for the EXTERNALLY facing piece.

**Comment by bsmithgall** [comment]
TODO:
- [ ] Mailing list signup functionality (MailChimp?) (Internal email capture?) (Both?) ([https://sendgrid.com/](Sendgrid?))
- [ ] What are the categories? Can we use NAICS codes?
- [ ] Content thinking -- do we want to do NIGP codes?

**Comment by hamhands** [comment]
Pursuing NAICS codes, testing suitability with Riley

**Comment by hamhands** [comment]
Moved to NIGP codes instead. Categorized, given go-ahead from Slim at OMB
