### ISSUE TITLE
Add scout logo

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#162]
Breaking out task from #145, add scout logo when @shellicious finishes the design.

**Comment by msknee** [comment]
Logo!

![scout_logo-03](https://cloud.githubusercontent.com/assets/1178390/9146363/029d9504-3d11-11e5-91e5-ec5e640d6f83.png)

**Comment by msknee** [comment]
Just binoculars:

![scout_logo_binoculars](https://cloud.githubusercontent.com/assets/1178390/9147918/5da30cce-3d23-11e5-8335-b0fd50ac13df.png)
