### ISSUE TITLE
Sometimes beacon categories return "None"

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#185]
From notification email:

```
A new vendor has signed up on beacon
Categories: COMMUNICATIONS AND MEDIA RELATED SERVICES (in Business services); None (in Business services)
```

**Comment by hamhands** [comment]
Found the problem.

These 8 records are the services Shelly added as they are not covered by existing NIGP categories. We could either a) make up some subcategories (although that seems weird as the whole point is that NIGP doesn't cover our needs here) or b) not use subcategories in our signup emails.

<img width="1205" alt="screen shot 2015-08-06 at 1 52 43 pm" src="https://cloud.githubusercontent.com/assets/3640800/9123130/71518606-3c42-11e5-8123-8aeee986bb8e.png">

**Comment by hamhands** [comment]
@bsmithgall let me know your thoughts on the above

**Comment by bsmithgall** [comment]
@hamhands fixing the email template to use the human readable name instead of the subcategory should fix that problem.
