### ISSUE TITLE
Add new section to "pending" page to show approved and not advertised opportunities

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#188]
The opportunity will show up in pending opportunities as public, even though the date for publishing is set to days in the future.

![screen shot 2015-08-06 at 1 30 59 pm](https://cloud.githubusercontent.com/assets/1178390/9123008/89887c76-3c41-11e5-8cb7-f846582eeb36.png)

![screen shot 2015-08-06 at 1 46 36 pm](https://cloud.githubusercontent.com/assets/1178390/9123015/98bc5884-3c41-11e5-8323-47f9fe7393a8.png)

**Comment by hamhands** [comment]
This raises a good question re flow. How do we want admins to review and publish opportunities for a future date? Do we want to not offer the ability to publish until that date comes, or do we want to let admins approve a post that will then automatically appear on the given date?

**Comment by hamhands** [comment]
This also might be more of an enhancement than a bug.

**Comment by msknee** [comment]
We fixed this with #187! 

opening another issue to address the fact that approved but not-yet-advertised opportunities currently disappear.
