### ISSUE TITLE
Consistent logos for Scout / Beacon / Conductor

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#192]
![screen shot 2015-08-08 at 10 45 56 am](https://cloud.githubusercontent.com/assets/1957344/9151565/b656d886-3dba-11e5-9778-9585c2a40da9.png)

**Comment by msknee** [comment]
time to change ALL THE LOGOS I was afraid of this happening.

**Comment by msknee** [comment]
For the time being, I uploaded a white version of the binoculars here: 
https://drive.google.com/drive/u/0/folders/0B24dyIgc537SfnphcktzdGQ0ZW9MbXVYN2JMQzU0cWJfdmdnajNEOFpNSkpPUm1sVHlfTjA

**Comment by msknee** [comment]
I've added the Scout and Beacon logos (small black versions for the navbar and large white versions for the circles) here: https://drive.google.com/drive/u/1/folders/0B24dyIgc537SZnk5cTZySnNSZUE

**Comment by msknee** [comment]
@hamhands ^^

Still not done is Conductor logo, which I'lll add to the logo folder before the end of the week

**Comment by msknee** [comment]
Uploaded Beacon logos that have skinnier linework: https://drive.google.com/drive/u/1/folders/0B24dyIgc537SZnk5cTZySnNSZUE
