### ISSUE TITLE
Improve documentation on conductor stage/flow/transition code

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#194]
Some of it is good, some of it is spotty. The function definitions are mostly ok, but inline commenting definitely needs work.

The best way to do this would probably be to sit down with someone and walk through it, documenting where the process is confusing.

**Comment by msknee** [comment]
is this captured by https://github.com/codeforamerica/pittsburgh-purchasing-suite/pull/378 ?

**Comment by bsmithgall** [comment]
The code is a lot better/cleaner, but not documented, so no.

**Comment by bsmithgall** [comment]
This is a partial duplicate of #482 work for this can be captured there, wontfixing here
