### ISSUE TITLE
In Contract List, add days counter

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#196]
- Show number of days that have passed since contract entered that step
- Display the original date of entry underneath the days counter (perhaps in black or gray, not bolded text?)

As brought up by @rileystewart and Ed during user testing.

**Comment by msknee** [comment]
@bsmithgall can I close this or are we waiting on a PR merge?

**Comment by bsmithgall** [comment]
these will all close automatically when #193 closes
