### ISSUE TITLE
Atlas-fy

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#197]
The remnants of Sherpa still _lurk_ within the suite. We must resolve this discrepancy lest we lead users astray in an ironic fashion.

**Comment by bsmithgall** [comment]
This is a partial duplicate of #52

**Comment by msknee** [comment]
I spy it in:
- [x] index page of The Suite
- [x] Apps dropdown
- [x] Navbar of Atlas
