### ISSUE TITLE
Remove star feature from Scout

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#203]
It is redundant.

Priority: done by monday 8/17

**Comment by bsmithgall** [comment]
:+1: removing code is good.

Here are places that it should be removed:
- [x] Search results page
- [x] User profile page
- [x] Filter by department page
- [x] Backend -- SQL query that builds the filter page

**Comment by bsmithgall** [comment]
We should actually totally remove it by taking it out of the database and removing all references to it in the codebase and migrating the database to delete the reference altogether, but that can be a separate task done later.
