### ISSUE TITLE
Post opportunities to beacon directly from conductor

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#207]
Offshoot of the mega-thread #121

**Comment by bsmithgall** [comment]
EXCITING PROGRESS

![autom8](https://cloud.githubusercontent.com/assets/1957344/9216499/0767eb46-406f-11e5-8ac6-2c56a59791c9.gif)

**Comment by msknee** [comment]
OOOO VERY NICE

**Comment by msknee** [comment]
AUTOMAGICAL
