### ISSUE TITLE
Rematch users against contracts they were following

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#219]
| UserId (Unchanged) | Contract ID (Old) |
| --- | --- |
| 4 | 27 |
| 4 | 292 |
| 4 | 558 |
| 4 | 241 |
| 4 | 247 |
| 4 | 586 |
| 4 | 20 |
| 2 | 284 |

**Comment by msknee** [comment]
has this been done?

**Comment by bsmithgall** [comment]
@hamhands ^
