### ISSUE TITLE
One-pager for e-signature services

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#222]
For meeting w/Paz on 8/25.

**Comment by bsmithgall** [comment]
@daguar says that he has some prior art around this from California/research.

**Comment by daguar** [comment]
https://github.com/codeforamerica/health/wiki/Research#electronic-signatures-in-ca

**Comment by msknee** [comment]
thanks @daguar!

**Comment by msknee** [comment]
Overview and comparison spreadsheet here: https://docs.google.com/spreadsheets/d/1jPRJ_N14bETeUW0goFQybVbrAegrdiucA9kyQ4rr_MI/edit#gid=1583737287

Will be taking content from this spreadsheet and condensing it into a visually appealing 1 or 2-pager

**Comment by msknee** [comment]
Prettified overview: https://docs.google.com/document/d/14Q0v5qn3mdaLLYRAZZIqfnRTMRYHd-9uhnRNOaoYz9c/edit#

Now 2 pages -- first is exec summary and comparison table, 2nd is implementation recommendations.
