### ISSUE TITLE
Rethink the company/contract relationship

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#223]
It feels like the many-to-many relationship isn't entirely accurate because you have a raft of currently separate contracts for the same thing that all expire on the same date. It's unclear how this works from conductor's perspective -- do you have to go through the renewal process for all of them? Or only for one? Are we over thinking this as an edge case?

**Comment by msknee** [comment]
@bsmithgall sounds like a question for Ed -- how does he renew or extend contracts that have multiple companies attached?

**Comment by bsmithgall** [comment]
This is more of a database/data model question, though how it is reflected in the UI is also a consideration.

**Comment by bsmithgall** [comment]
WONTFIX on this
