### ISSUE TITLE
Enter email contacts into Conductor staging

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#235]
- [x] County agent emails
- [x] Should we enter 1 email per City department, or wait for departmental email lists to populate from Scout usage? (checked because we're waiting for departmental lists to naturally populate)

**Comment by bsmithgall** [comment]
Given the current scout usage, I think we are probably ok on that front.

**Comment by msknee** [comment]
Success!

![screen shot 2015-08-23 at 10 20 23 pm](https://cloud.githubusercontent.com/assets/1178390/9433286/3cf7b488-49e5-11e5-8139-1ee28d4df1f2.png)
