### ISSUE TITLE
Get Ready for production (alpha)

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#24]
Here are a list of tasks that need to be done before we can deploy:
- [x] Whitelist pittsburghpa.gov emails and autoassign them to staff roles, create a new post-login view that let's them set their department (and return/manage it in the future).
- [x] Add more robust logging
- [x] Handle static assets (either using Heroku bin scripts/full Dockerfile and an installed less precompiler, or migrating full on to S3 for static assets)
- [ ] Set up S3/dropbox/some other service to hold COSTARS contract documents
- [x] Add indices to the database
- [x] Added search for line items, contract properties. Potentially optimize these queries and/or add indices to the database to make things faster than mud.
- [ ] Visual style walkthrough with @shellicious 
- [x] Go through remaining [checklist for deployment-readiness](https://github.com/codeforamerica/howto/blob/master/launch_requirements.md)
- [x] Add to enginelight (switch with Wexplorer)
- [x] Update README with Sherpa information
- [x] Heroku doesn't support writing logs to files, so do something else instead of using a FileHandler (ask around on Slack, look at Heroku addons)
- [x] Try (harder!) to actually mock the Govbids thing.

**Comment by bsmithgall** [comment]
@shellicious do you have time to make a favicon by Friday?

**Comment by msknee** [comment]
@bsmithgall it'll be pretty basic but I can do eet
