### ISSUE TITLE
Scout showing expired contracts

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#241]
When I search Staples in scout, expired contracts are showing up in the results even without the include archived checked.

**Comment by bsmithgall** [comment]
This raises the question -- how do we handle expiring/soon to expire contracts in scout? Right now, we just show everything.

**Comment by rileystewart** [comment]
If it has expired do not show it during search. it should show up in admin though

**Comment by bsmithgall** [comment]
Not at all? I feel like it would be good expose it with a warning, at least for a few weeks after the expiration so that things don't just disappear on people. Thoughts @shellicious ?

**Comment by rileystewart** [comment]
if it shows up ppl will try to use it. it won't get paid and potentially it may be a contract that we are not renewing/extending.  they could still check the 'archived' box to have it appear and then contact us about that old contract but we only want current valid contracts showing to departmental users

**Comment by msknee** [comment]
Hmm. Good points @rileystewart and @bsmithgall.

#### New categories to use in Scout
- **Expiring soon**: Show up in search results with a warning icon, or change in text color of expiration date (@shellicious to post explorations shortly) for contracts that are expiring in 120 days. (@rileystewart, should the warning window be less time, like 90 days? 60?)
- **Inactive**: Contracts that fall into this category do not show up in search results, unless the person searching checks a "Show inactive" box.  @shellicious to open a separate, less high priority issue to explore warning icons / ways of indicating the following subcategories:
  - **Expired**: Contracts past their expiration date.
  - **Replaced**: Contracts that have completed a Conductor flow (renewal or bidding out), and have been replaced.
  - **Manually archived**: Contracts that have been removed for active use for other reasons.
  - Any 1 state of the above states can cause a contract to become inactive, and thus not appear in search results without checking the box. For example, a contract can be replaced before it has expired. 

#### To-do's
- [x] Change the wording of "show archived" filter to "show inactive"
- [x] Do not show expired, replaced, or manually archived contracts in search results unless the "Show inactive" box is checked.
- [x] Add warning icon to contracts in search results that are expiring in 120 days.
