### ISSUE TITLE
Scout Admin not showing contracts

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#242]
I'm trying to delete a contract that was accidentally put into scout.  When I search staples in admin only one contract appears when there are 4.

**Comment by hamhands** [comment]
<img width="1184" alt="screen shot 2015-08-19 at 10 51 05 am" src="https://cloud.githubusercontent.com/assets/3640800/9364245/3be4cf82-4660-11e5-985c-7f27be4014e6.png">

**Comment by bsmithgall** [comment]
This is related to #237.

**Comment by bsmithgall** [comment]
This is fixed by #239
