### ISSUE TITLE
get error when trying to add new contract

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#243]
trying to add new state contract and get an error message when i hit submit or save/add

Failed to create record. (psycopg2.DataError) integer out of range [SQL: 'INSERT INTO contract (financial_id, created_at, updated_at, contract_type, expiration_date, description, contract_href, flow_id, current_stage_id, assigned_to, department_id, is_visible, is_archived, parent_id) VALUES (%(financial_id)s, %(created_at)s, %(updated_at)s, %(contract_type)s, %(expiration_date)s, %(description)s, %(contract_href)s, %(flow_id)s, %(current_stage_id)s, %(assigned_to)s, %(department_id)s, %(is_visible)s, %(is_archived)s, %(parent_id)s) RETURNING contract.id'] [parameters: {'department_id': None, 'current_stage_id': None, 'is_archived': False, 'parent_id': None, 'created_at': datetime.datetime(2015, 8, 19, 18, 30, 1, 597353), 'is_visible': True, 'description': u'AFTERMARKET PARTS', 'flow_id': None, 'assigned_to': None, 'contract_href': u'', 'updated_at': datetime.datetime(2015, 8, 19, 18, 30, 1, 597417), 'financial_id': 4400014638, 'contract_type': u'STATE', 'expiration_date': datetime.date(2016, 6, 30)}]

**Comment by bsmithgall** [comment]
This is due to [postgres integers being 4 bytes](http://www.postgresql.org/docs/9.1/static/datatype-numeric.html)

The fix is to migrate the contract table to make the financial_id field a string type and do type coercion on all of the forms.
