### ISSUE TITLE
On contract detail page, show specific inactive category

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#246]
If a contract is inactive, display an alert box on the detail page that explains:
- [x] Expired: "This contract is expired and is not usable anymore."
- [x] Replaced: "This contract has been replaced with {{ link to new contract }}."
- [x] Expired AND replaced: "This contract is expired, and has been replaced with {{ link to new contract }}."
- [x] Manually archived: "This contract has been removed from use."
- [x] Manually archived and replaced: "This contract has been removed from use, and replaced with {{ link to new contract }}."

**Comment by bsmithgall** [comment]
**Replaced**
![screen shot 2015-08-19 at 4 19 38 pm](https://cloud.githubusercontent.com/assets/1957344/9371982/433b8392-468e-11e5-9c6e-146e9d3d0f54.png)

**Expired**
![screen_shot_2015-08-19_at_4 05 01_pm](https://cloud.githubusercontent.com/assets/1957344/9371978/3c3153f6-468e-11e5-98de-68a40b639dac.png)

**Comment by msknee** [comment]
Can you get rid of the Warning! text? Otherwise, :+1: :+1:
