### ISSUE TITLE
No favicon!

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#248]
We should have one, especially because it's throwing 403/404 errors in production.

**Comment by msknee** [comment]
Added 2 favicon candidates here. Keep the one you think looks best: https://drive.google.com/drive/u/0/folders/0B24dyIgc537SfkdZV3FUTGJDd1dMX2ZSZmY3Ri1Rd1ZBQk9XdGhKamFtV2FobEF6cDNRTUE
