### ISSUE TITLE
Semantics are very confusing for beacon posting form

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#261]
Both **advertised** and **open** have very specific meanings in procurement land, leading to a ton of confusion with the beacon form from both Slim & Stephanie.
- **Advertised** means that the opportunity has been sent to a newspaper in general circulation
- **Open** means that the responses to the opportunity have been opened.

Slim recommends that we changed "advertised" to "published," and move open/deadline to "submissions start" & "submissions end"

cc @shellicious

**Comment by msknee** [comment]
I agree with Slim's suggestions for new copy. We'll need to:
- [x] Change them all ova Beacon
- [x] Change them in the walkthrough

And we should do them by tomorrow before office hours.

**Comment by bsmithgall** [comment]
You should also update the model methods & tests for consistency.

**Comment by msknee** [comment]
Found another issue: opportunity status was not showing up when an opportunity had no categories. Made a simple HTML fix and now the status shows up no matter what.

Example:

![screen shot 2015-08-24 at 2 51 00 pm](https://cloud.githubusercontent.com/assets/1178390/9453601/59609230-4a70-11e5-9a99-935cb0fb5493.png)

Fixed now:

![screen shot 2015-08-24 at 2 54 51 pm](https://cloud.githubusercontent.com/assets/1178390/9453629/826c610e-4a70-11e5-9c80-805e2d85f242.png)

![screen shot 2015-08-24 at 2 55 11 pm](https://cloud.githubusercontent.com/assets/1178390/9453615/6d6e119e-4a70-11e5-8438-39a0ce9f5c89.png)
