### ISSUE TITLE
Pending view has incorrect advertise/open/deadline dates

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#265]

**Comment by msknee** [comment]
Fixed!

Dates inputted:
![screen shot 2015-08-24 at 2 11 50 pm](https://cloud.githubusercontent.com/assets/1178390/9452613/1db6eef6-4a6a-11e5-8366-17bc0d5a9005.png)

Dates now displayed:
![screen shot 2015-08-24 at 2 11 29 pm](https://cloud.githubusercontent.com/assets/1178390/9452614/1db79ac2-4a6a-11e5-8df1-3c301e47a21a.png)
