### ISSUE TITLE
There's no sensible way to "start new" on Conductor, which is problematic

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#276]

**Comment by msknee** [comment]
like, start a new opportunity post?

**Comment by bsmithgall** [comment]
No, a new contract.

**Comment by bsmithgall** [comment]
Thanks for the title change, I'm just a little loopy today

:confused:

**Comment by bsmithgall** [comment]
@shellicious, did you get a chance to put together a wireframe with how this would work? I'd like to tackle some conductor work this week.

**Comment by bsmithgall** [comment]
Some screenshots:

![screen shot 2015-09-08 at 3 18 21 pm](https://cloud.githubusercontent.com/assets/1957344/9748880/e30033ec-563c-11e5-92e0-2427ff80124a.png)

![screen shot 2015-09-08 at 3 17 52 pm](https://cloud.githubusercontent.com/assets/1957344/9748869/d097b8e2-563c-11e5-8c1f-f9f5a83117b2.png)
![screen shot 2015-09-08 at 3 17 41 pm](https://cloud.githubusercontent.com/assets/1957344/9748868/d096b88e-563c-11e5-9e7d-385eb4befe97.png)
![screen shot 2015-09-08 at 3 17 58 pm](https://cloud.githubusercontent.com/assets/1957344/9748867/d0835b86-563c-11e5-9fbc-621b22e3a8a5.png)

**Comment by msknee** [comment]
Looks good! 

Changes:
- Change text of "start new contract" to "add new contract"
- Turn link to white text on a blue button
- right align it

**Comment by bsmithgall** [comment]
![screen shot 2015-09-10 at 9 54 42 am](https://cloud.githubusercontent.com/assets/1957344/9794800/fa724888-57a1-11e5-8fcf-93f8e325c60c.png)

**Comment by msknee** [comment]
Text should be in regular caps: "Add new contract", and icon isn't necessary.

**Comment by bsmithgall** [comment]
It looks a little sad without the icon, no?

![screen shot 2015-09-10 at 12 06 17 pm](https://cloud.githubusercontent.com/assets/1957344/9798211/67bbde6a-57b4-11e5-8646-9b24d2d768c9.png)

**Comment by msknee** [comment]
i have an idea! commenting on #299 first, then will post a thing here

**Comment by msknee** [comment]
Option 1: place add contract button under 'all contracts', where it makes more sense contextually, change styling of filtering buttons, and place them all in a row:

![contractlist3](https://cloud.githubusercontent.com/assets/1178390/9801162/67e377ce-57df-11e5-8b2b-29f1e8fa1477.png)

Option 2: Difference between this and option 1 is the "show 10 entries" button is shaded too. It is 'on' in both options, but only called out as an active filter in this one.

![contractlist2](https://cloud.githubusercontent.com/assets/1178390/9801218/b827945e-57df-11e5-962f-c9dabc11ffda.png)

**Comment by bsmithgall** [comment]
Unfortunately, due to limitations of datatables, I don't have a ton of control over the way different things render, and I can't figure out a good way to inline everything. How's this:

![screen shot 2015-09-10 at 4 35 32 pm](https://cloud.githubusercontent.com/assets/1957344/9803701/0a01160c-57da-11e5-9962-a64e5926003f.png)

**Comment by bsmithgall** [comment]
![autom8](https://cloud.githubusercontent.com/assets/1957344/9803838/f5b9c480-57db-11e5-9951-846b6e946552.gif)

**Comment by msknee** [comment]
That's fine
