### ISSUE TITLE
The date for the "in-progress" current step is a bit confusing

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#279]
"Why is it there? What does it mean?"

I think this is a valid criticism. Maybe we should add a little flag, or "work started" to the event sidebar?

**Comment by msknee** [comment]
This seems addressed by changes in #310. Can I close this @bsmithgall?

**Comment by bsmithgall** [comment]
Let's leave it open until changes are merged.

**Comment by msknee** [comment]
#310 is closed and merged, closing this issue.
