### ISSUE TITLE
Compile a list of all potential bid documents that vendors might need, and their descriptions

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#281]
This is a start:
- Bid bonds
- Performance bonds
- Insurance certificates

**Comment by msknee** [comment]
Added content to https://www.buildpgh.com/admin/bid_document/

![screen shot 2015-09-16 at 4 34 02 pm](https://cloud.githubusercontent.com/assets/1178390/9921280/c9a5ff8a-5c90-11e5-8b2c-0858839e635c.png)
