### ISSUE TITLE
See list of vendors is a company?

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#288]
Surfaced by Dave Osterman:

If you go to https://www.buildpgh.com/scout/companies/2212, you see a list of contracts and contacts from four different companies, but no real vendor information.

**Comment by bsmithgall** [comment]
"See list of vendors" was on the x-drive, so it got imported like everything else. Without any additional information about breaking these up, it's pretty difficult to know what to do. I think @rileystewart will have to handle this one...

**Comment by hamhands** [comment]
More questions about this from Kate Weiland...

**Comment by bsmithgall** [comment]
We should just rename this to something else as a stopgap measure for now @rileystewart
