### ISSUE TITLE
County Number, spec# problem

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#289]
From Dave Osterman:

For contracts with multiple vendors, the county number is pretty important.

For example, [Fletcher](https://www.buildpgh.com/scout/contracts/2277) and [EH Griffith](https://www.buildpgh.com/scout/contracts/2276) are both on this contract, but Scout assigns an incorrect spec# for Fletcher (should be 7396, same as EH Griffith)

If you look at the [actual contract](http://apps.county.allegheny.pa.us/BidsSearch/pdf/7396.pdf), you can see the two different county numbers (48359 vs 48467).

**Comment by bsmithgall** [comment]
Fix the spec number in the admin, add the county numbers as additional properties in the admin.

**Comment by bsmithgall** [comment]
Is this resolved?

**Comment by hamhands** [comment]
@bsmithgall for this specific case yes the data was updated. The larger county number issue is still obviously an open question, but I think we can close this.
