### ISSUE TITLE
Profile app link

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#290]
When signing in and updating profile, link to app goes away:
<img width="1280" alt="screen shot 2015-08-26 at 12 28 31 pm" src="https://cloud.githubusercontent.com/assets/3640800/9499557/0ad601b6-4bee-11e5-9919-26fbf2e1074e.png">

Confused users are confused.

**Comment by bsmithgall** [comment]
This is because we disabled everything @hamhands

**Comment by hamhands** [comment]
Right. So I guess we should upgrade the stop gap fix to a full fix

**Comment by bsmithgall** [comment]
? What does that mean? I think we might want to add the app links back in there.

**Comment by hamhands** [comment]
@bsmithgall I mean commenting out all app links in the global nav bar always struck me as a stop gap rather than a real fix.

**Comment by bsmithgall** [comment]
What's the plan here, it is awkward to try to move between apps now. Do we have any thoughts on turning something back on for this @shellicious @hamhands ?

**Comment by hamhands** [comment]
@bsmithgall the original impetus for removing app links was when scout was launched. I don't know what @shellicious thinks, but in my mind I think there at minimum needs to be some way to get back to the app the user came from when editing profile info or signing up for an account. That's currently pretty difficult to do, right?

**Comment by bsmithgall** [comment]
Yes.

**Comment by bsmithgall** [comment]
We originally had a way to navigate between the apps, but that is gone now.

**Comment by hamhands** [comment]
Other option is that we turn all app links back on, but that would a) muddy up the already fairly full nav bar and b) possibly confuse users as @rileystewart originally noted. Maybe now that all the apps have been out and in use for a couple months now, that's less of a concern though.

**Comment by bsmithgall** [comment]
Ok, I think that's the right way to do it, thoughts @shellicious?

**Comment by msknee** [comment]
at one point, we had links in a drop down. Is that what you're suggesting bringing back, @hamhands? I'm in favor of that. I was just thinking yesterday that navigating between apps is an annoyance.

**Comment by bsmithgall** [comment]
@hamhands do you want to re-add them?

**Comment by bsmithgall** [comment]
While you are at it, you can probably fix #490

**Comment by hamhands** [comment]
@bsmithgall :+1:
