### ISSUE TITLE
Amp up warning messages

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#294]
User testing with Cas this morning, the warning messages were being skipped over or ignored pretty regularly. This has come up with other users as well. 

<img width="1179" alt="screen shot 2015-08-26 at 1 35 40 pm" src="https://cloud.githubusercontent.com/assets/3640800/9501140/60b7d3b2-4bf7-11e5-8b1e-3b02459dbb76.png">

Typical flow goes something like this:
- Tries to subscribe, doesn’t see warning message first time, gets confused
- Does it again, sees message, doesn’t read it, moves on
- After prompting, reads the message, goes through sign-in process
- No issue with sign up flow, creates profile
- Doesn’t see “updated your profile” message, gets confused, clicks submit multiple times
- Heat death of the universe

**Comment by msknee** [comment]
Which other users has this come up for?

I bet it's because they're not used to this style of alert, and the place they're clicking/focusing on is not close enough to the top of the page for them to notice the alert appearing.  

We could do something more disruptive, like a pop-up alert, but I don't want to go there unless this is widespread.

Still thinking about more elegant solutions than a pop-up.

**Comment by hamhands** [comment]
@shellicious It came up a couple of times during office hours today. In particular, Stephanie asked a question about signing up (see #290) and this issue came up.

**Comment by msknee** [comment]
Got it.

For the specific issue of people not getting the hint that they need to log in / being unsure of where to log in:

I'm always in the Prevention First camp. We could change the button to a link that says "Log in to Subscribe" if the user is anonymous, and then back to the "Subscribe for updates" button once the user is logged in as city staff / conductor / admin.

For the separate issue of people not reading the "profile updated!" message...something to try:
- the "submit" button switches text to "submitting..." after it's clicked. @bsmithgall is this a relatively simple thing to do? 
- make the alert much bigger. Like a big green check icon appears to indicate success.
