### ISSUE TITLE
Decide on colors for Conductor activity stream

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#299]

**Comment by bsmithgall** [comment]
I think that some icons could be really helpful too for quick encoding (this was mentioned when I brought it up with some people today)

**Comment by bsmithgall** [comment]
- [ ] Mail 
  - Icon: http://fontawesome.io/icon/envelope-o/
  - Color:
- [ ] Note
  - Icon: http://fontawesome.io/icon/sticky-note-o/
  - Color:
- [ ] Started Work
  - Icon: http://fontawesome.io/icon/play/ (or, http://fontawesome.io/icon/hourglass-start/ with end on stopped)
  - Color:
- [ ] Stopped Work
  - Icon: http://fontawesome.io/icon/check/ (or, http://fontawesome.io/icon/hourglass-end/ or http://fontawesome.io/icon/flag-checkered/)
  - Color:
- [ ] Update metadata
  - Icon: http://fontawesome.io/icon/pencil-square-o/
  - Color:
- [ ] Post to beacon
  - Icon: http://fontawesome.io/icon/paper-plane-o/ (or http://fontawesome.io/icon/rocket/ !)
  - Color:
- [ ] Revert
  - Icon: http://fontawesome.io/icon/repeat/
  - Color:
- [ ] Flow switch
  - Icon: http://fontawesome.io/icon/exchange/
  - Color:

**Comment by bsmithgall** [comment]
Updated with some potential icons

**Comment by bsmithgall** [comment]
Screenshot:

![screen shot 2015-09-08 at 5 41 24 pm](https://cloud.githubusercontent.com/assets/1957344/9750746/e4418030-5650-11e5-9fc8-98b18159e200.png)

**Comment by msknee** [comment]
:+1: the icons.

I like http://fontawesome.io/icon/circle-o/ for starting work on a step, and http://fontawesome.io/icon/circle/ for completing a step.

Or for more fun, http://fontawesome.io/icon/rocket/ for starting a step (h/t Ed) and the check mark for completing a step.

Tweaks:
- [x] bold the name of the step in the activity stream, to match the noun-bolding pattern (email address, name of note, etc.) in the other actions. Unbold the name of the action.
- [x] Change date display to mm/dd/yy in the overall timeline on left, and in individual steps on the right

**Comment by bsmithgall** [comment]
![screen shot 2015-09-09 at 2 41 37 pm](https://cloud.githubusercontent.com/assets/1957344/9774997/eb931118-5700-11e5-9942-4bdfee7eb7e3.png)

**Comment by bsmithgall** [comment]
Good color encoding would really round this out, I think.

**Comment by msknee** [comment]
Yeah. Try:
- Green for start / end logs for completed steps
- Blue for start log for current step
- Gray for logs for actions taken in a step, current or completed (can't think of a better color at the moment. gray looks good, but is also used to denote steps not yet reached, which is mixing meanings in a way that probably only bothers me)

Is it confusing if we stick to this color scheme for stages you've jumped back to? I skew towards using less colors -- any more than 3 or 4 and meaning gets diluted. 

Let's try it out and see what it looks like. @bsmithgall, post a screenshot when you get to this?

**Comment by msknee** [comment]
Also, the no-label filter icons need labels, since I have a hard time figuring out what they do / remembering what they do.

I suggest adding these labels to the right of each icon:
- [ ] Notes
- [ ] Emails
- [ ] Beacon
- [ ] ? not sure what this one is
- [ ] Stages

**Comment by bsmithgall** [comment]
![screen shot 2015-09-10 at 9 36 12 am](https://cloud.githubusercontent.com/assets/1957344/9794337/6aaeba80-579f-11e5-9988-bb4de14e4045.png)

**Comment by msknee** [comment]
Tweaks:
- [x] Add 5-10 px of space between the icon and the label

Icon changes:
- [x] Notes: http://fontawesome.io/icon/pencil/
- [x] Beacon: http://fontawesome.io/icon/bullhorn/
- [x] Metadata: http://fontawesome.io/icon/file-text-o/
- [x] Stages: http://fontawesome.io/icon/circle-o/
- [x] Start work: http://fontawesome.io/icon/circle-o/
- [x] Complete work: http://fontawesome.io/icon/circle/ (if it looks weird, go with http://fontawesome.io/icon/check-circle/)

**Comment by bsmithgall** [comment]
![screen shot 2015-09-10 at 3 42 53 pm](https://cloud.githubusercontent.com/assets/1957344/9803085/26cb9574-57d4-11e5-90ee-88667525b899.png)

**Comment by msknee** [comment]
:+1: :+1: :+1: :+1: :+1:
