### ISSUE TITLE
when attaching costars pdfs I get an error 

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#301]
When in admin in conductor linking contracts, it gives me an error screen when I hit upload.

Request Entity Too Large

The data value transmitted exceeds the capacity limit.

**Comment by bsmithgall** [comment]
Is this for all of them? I think we put an upload limit of 2MB on files, but I can increase it.

**Comment by bsmithgall** [comment]
How big is the file you are attaching @rileystewart ?

**Comment by rileystewart** [comment]
14,000kb

**Comment by rileystewart** [comment]
there are some that are up to 34,000kb

**Comment by rileystewart** [comment]
take that back. biggest is 55,000kb

**Comment by bsmithgall** [comment]
I upped the max file upload size to 60MB @rileystewart so go ahead and try again.
