### ISSUE TITLE
creates duplicate entries if you hit submit twice

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#303]
was in admin adding a new contract.  Hit submit.  was taking a long time loading....realized the expiration date was wrong.  changed and hit submit again.

checked after and it had created 2 contracts.

**Comment by bsmithgall** [comment]
The slowness on the admin is something that we are working on that should be addressed by some of the work around #38 -- for now, just make sure it loads all the way before you try to submit again. You can go ahead and delete the duplicate if you haven't already.
