### ISSUE TITLE
remove/add years to expiration date drop down

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#304]
from admin add contracts there are lots of years that have already passed and not that many that are in the future.  Would rather refine this to 2 years in the past and 10 in the future if possible.  we're trying to get longer and longer contracts.

**Comment by bsmithgall** [comment]
I'll look into this, but you should be able to manually write in whatever you need. Just make sure it is in the proper format.

**Comment by bsmithgall** [comment]
@rileystewart If you need to go into the future, you can scroll through them. For example, if you select 2020, it will automatically populate the next few years into the future. You should be able to do this basically forever.

Screenshot:

![screen shot 2015-09-08 at 9 35 02 am](https://cloud.githubusercontent.com/assets/1957344/9741041/fb200982-560c-11e5-8b50-e030399f2052.png)
