### ISSUE TITLE
Some feedback on Beacon welcome email from Rebecca Harris

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#305]
Welcome email
- Should be more like a welcome packet
  - Make sure to share what _exactly_ beacon does
- Also point people to BidNet directly (register to be on there for free)
- Maybe also point to other known places

Front page
- Should have additional contact information (phone numbers?)
- How do people know that this is legitimate? Would it be possible to get a city seal/seal of the Department of I&P to put in the footer or somewhere else?
- There's no real way to know what Beacon ~is~ actually
- Nothing about the professional services on the front page
- The text right under the "The City of Pittsburgh could be..." isn't right. Maybe something along the lines of "The City of Pittsburgh needs to buy what you sell. Sign up to get notified about..."

About page
- A bit about CfA, a bit about our partnership with the City.

Other
- Is there any way to piggyback on the Mayor's Innovation Roadmap announcement? (September 8, should be in email, see Slack also)

**Comment by msknee** [comment]
Breakdown into tasks:
- [x] Add city seal to the footer
- [ ] Maybe add Kevin's email address?
- [x] Change text on splash image to be more specific
- [x] Add professional services to FAQ on front page

Nice to have but not critical is:
- [x] About page: other users have not asked about it

**Comment by bsmithgall** [comment]
Is all work finished on this?
