### ISSUE TITLE
Confusion about assigning contracts

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#308]
### Highlights from OMB meeting:
- There is a need for contracts to be assigned to one person for life
- When someone calls with an issue about a contract, even after adoption, to know who worked on it before

I think we have a couple options here:
1.  Automatic assignment
   - Riley: assigning only happens with completely new contracts. Everyone has their own pool of contracts for as long as the contract is held or renewed or re-bid, etc.
   - Example: I have sports contracts because I worked with similar things last year
   - In this flow, the only time assignment would happen is for completely new contracts
2. Change the assignment language to something like "Work on this contract"

**Comment by bsmithgall** [comment]
If we do automatic assignment, we'll need some way to get the historical data. We could do some bulk importing, but honestly I don't _really_ understand why they can't just do it themselves.

Either way, we need to change the "assign" experience off of the list view to capture both the person doing the work _and_ the flow that is needed. Thoughts on how this should work @shellicious ?

**Comment by msknee** [comment]
I like option 2. The assigned to column shows the first name (or for the time being, email) of the person assigned. Add a "work on this" button in the name cell of the row (where the "Update this contract" button shows up in the in-progress rows).

**Comment by bsmithgall** [comment]
Move assign into actions as "start work" which takes you to the same page as the "new" page, add controller number to table.

**Comment by bsmithgall** [comment]
![autom8](https://cloud.githubusercontent.com/assets/1957344/9820991/456004c8-586c-11e5-8d42-7c54e776bda7.gif)

**Comment by hamhands** [comment]
That flow makes sense to me. Let's see if it makes sense to Ed next week.
