### ISSUE TITLE
Stage card additions

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#309]
### From OMB meeting:

Ed: _what if there were a counter in each stage so we know how long it took?_
- I think the main thing here is that there should be some kind of count available in the stage card itself. What this actually looks like is an open question.
- Also need to add who took a certain action in cases where someone updates a contract not assigned to them
- How close contract is to expiring needs to be present somewhere in the update screen, whether on the stage card or elsewhere

**Comment by bsmithgall** [comment]
That's an interesting and pretty simple to implement idea (at least from the backend perspective). A more interesting open question has to do with stage updating -- should anyone be able to mark anyone else's work as complete (currently there are no permission locking, everyone can do everything assuming they have access to conductor in the first place).

**Comment by bsmithgall** [comment]
Screenshot of the new and improved event cards 
![screen shot 2015-09-09 at 2 59 46 pm](https://cloud.githubusercontent.com/assets/1957344/9775375/87c4c818-5703-11e5-9c06-f957fdaebba6.png)

**Comment by msknee** [comment]
LOOKS SO GREAT
