### ISSUE TITLE
Sherpa pilot plan

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#31]
People to reach out to who might need a contract (professional services agreement) started in June, or who would be good to ask:
- [ ] Stephanie Haugan, Personnel
- [ ] Cas Pelligrini, Public Works
- [ ] Matt Stidle / Yvonne / Lourdes, Law
- [ ] Jim / Louann at Parks

**Comment by bsmithgall** [comment]
wontfixing and closing
