### ISSUE TITLE
High-level note tracking

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#310]
### From OMB meeting
- Some concern about having meta notes rather than stage-specific notes
- Might be a need to hand down information about a contract if renewed or re-bid
- Way to see all notes rather than having to click a stage
- Need for high-level notes about contract

**Comment by bsmithgall** [comment]
Questions -- where would this live/how would it be a part of the interface? We don't have a _ton_ of space to work with at the moment.

Is this/could this be related to the contract-specific notes that currently exist on Scout?

**Comment by msknee** [comment]
Potential solution: detail view always expanded, with little bit of javascript + "#" anchors so current stage is automatically scrolled to.

**Comment by bsmithgall** [comment]
In thinking about this, it seems like the current interface for the detail view isn't really able to handle this in a decent/elegant way. I was talking to @mapsam and @AmirHadjihabib about this and here are a few different approaches:

**Basic layout changes**

1: Split the current stage out from the activity stream
![screen shot 2015-09-08 at 4 51 36 pm](https://cloud.githubusercontent.com/assets/1957344/9750262/3493b08c-564a-11e5-9e68-377517bfa1e3.png)

2: Split the current stage out from the activity stream and also move it over to the same column as the event well
![screen shot 2015-09-08 at 4 50 04 pm](https://cloud.githubusercontent.com/assets/1957344/9750263/34948606-564a-11e5-8f03-43ec9af9ce1a.png)

**Changes to the time cards (using number 1 from above, related to #309)**

1: Smaller stage heights for not-yet-started stages
![screen shot 2015-09-08 at 5 02 07 pm](https://cloud.githubusercontent.com/assets/1957344/9750364/88e5417c-564b-11e5-9938-9fe3cb4fa380.png)

2: Better stage card definitions
![screen shot 2015-09-08 at 5 15 00 pm](https://cloud.githubusercontent.com/assets/1957344/9750475/2bb971d8-564d-11e5-863c-8c83cb9d9885.png)

**Comment by mapsam** [comment]
:+1:

**Comment by msknee** [comment]
I like the last version (2: Better stage card definitions the best). :+1: to shortened stage heights!

Do additional actions (send email, post to Beacon) show up as tabs under 'activity stream'?

**Comment by bsmithgall** [comment]
Yeah, see the screenshot in #299

**Comment by msknee** [comment]
I see the log in #299 but not how to tabs or buttons for the actions

**Comment by bsmithgall** [comment]
Oh! Is this what you mean

![screen shot 2015-09-09 at 12 57 50 pm](https://cloud.githubusercontent.com/assets/1957344/9772665/6b467008-56f2-11e5-9916-03ab4c0445be.png)

**Comment by msknee** [comment]
Yeah! I'd like to see the action area in its own gray box above the activity stream in its own box, or in the same box as the activity stream and also on top of it. Otherwise, it could be take lots of scrolling to find it

**Comment by msknee** [comment]
Oops accidental closing

**Comment by bsmithgall** [comment]
![screen shot 2015-09-09 at 1 07 57 pm](https://cloud.githubusercontent.com/assets/1957344/9772897/d43c7a8e-56f3-11e5-8fae-1dc52791c69e.png)

**Comment by msknee** [comment]
Hmm. I actually like it on the bottom better. Maybe scrolling isn't so bad.

It does need a title! Call it "actions".

**Comment by bsmithgall** [comment]
Filters!

![autom8](https://cloud.githubusercontent.com/assets/1957344/9773517/919d9466-56f7-11e5-8c64-8fab844200f3.gif)

**Comment by msknee** [comment]
OOO FILTERS

**Comment by bsmithgall** [comment]
Filters take 2

![screen shot 2015-09-09 at 2 32 16 pm](https://cloud.githubusercontent.com/assets/1957344/9774805/b3893c58-56ff-11e5-84b2-d2b0e138f714.png)
![screen shot 2015-09-09 at 2 32 06 pm](https://cloud.githubusercontent.com/assets/1957344/9774804/b38602b8-56ff-11e5-959b-97020dabafa0.png)
