### ISSUE TITLE
Historical metadata (“Legacy”) page

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#311]
### From OMB meeting:
- Seeing history of contract in one detail page? 
- Old contacts, how long each step took, when it expired, notes about vendor quality, etc.
- Connecting current contracts with expired ones

**Comment by hamhands** [comment]
:arrow_up: Those might need to be broken up

**Comment by bsmithgall** [comment]
This already exists, we just need to expose it, similar to how we do it in Scout.
