### ISSUE TITLE
Assign contracts to multiple departments

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#312]
Instances where contracts are split between contracts aren't currently possible (e.g. Fire & EMS with medical supplies contracts). This should be captured somehow.

**Comment by bsmithgall** [comment]
This would involve a migration, but would be doable. Should we do it though?

**Comment by msknee** [comment]
Answer to the August 27 question: no

**Comment by hamhands** [comment]
@shellicious doesn't that contradict our decision to allow multiple departments in the conductor > beacon flow? I remember citing EMS specifically.
