### ISSUE TITLE
Additions to contract list

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#314]
From OMB meeting:

At-a-glance information requested in contract list view (like a plus sign to expand each row):
- Using dept
- Contact info
- Controller #

**Comment by bsmithgall** [comment]
Is the contact info for the using department? If so, how do we know what to display? Is it the same stuff that's in the email bit?

For controller numbers, we're in the same confusing position as we are for spec numbers, as contracts that are currently "in progress" in conductor don't actually have this information associated with them.

**Comment by bsmithgall** [comment]
Some possible ideas
- Some ability to toggle show/hide on columns
- Tooltips/hovers to get additional information
- Add more information to the "Name" column (such as using department/department contact)

**Comment by bsmithgall** [comment]
@hamhands @shellicious still not sure what to do about the contact information. Is that contained in the tracking spreadsheet somewhere? I feel like we should be smart about how we handle that.

**Comment by bsmithgall** [comment]
Doing this in datatables isn't actually super complex:

![autom8](https://cloud.githubusercontent.com/assets/1957344/9780861/d023f342-5742-11e5-9659-c8dba43f7410.gif)

**Comment by bsmithgall** [comment]
How do we feel about this?

![screen shot 2015-09-11 at 9 57 52 am](https://cloud.githubusercontent.com/assets/1957344/9820854/98f069a8-586b-11e5-971f-16ae66f3c05b.png)

**Comment by hamhands** [comment]
I think that looks pretty good. Plus there's enough space to add more properties if they ask for them later.

**Comment by msknee** [comment]
I'd like to see it without the outer border around the table. Looks good tho!
