### ISSUE TITLE
Need test for all the semantics changes in templates

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#316]
Ran into a jinja error on the [opp detail template](https://github.com/codeforamerica/pittsburgh-purchasing-suite/blob/master/purchasing/templates/opportunities/front/detail.html) and I'm sure it's elsewhere.

The one in particular had to do with `estimate_open()` and `estimate_deadline()` (they changed to `estimate_submission_start()` and `estimate_submission_end()` in the model)

**Comment by bsmithgall** [comment]
Is this a currently a breaking problem in production?

**Comment by hamhands** [comment]
No, because the semantics changes haven't been pushed yet

**Comment by bsmithgall** [comment]
So one of the open PRs will cause breaking changes? If so, that PR should probably not be merged...

**Comment by hamhands** [comment]
It's not currently breaking anything that I know of, but it did break the
browse opportunity template and everything passed fine. There _could_ be
breakage.

On Fri, Aug 28, 2015 at 9:52 AM, Ben Smithgall notifications@github.com
wrote:

> So one of the open PRs will cause breaking changes? If so, that PR should
> probably not be merged...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/pittsburgh-purchasing-suite/issues/316#issuecomment-135780229
> .

## 

Patrick Hammons
@hamhandedly
