### ISSUE TITLE
Parent categories not fully deduped

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#33]
![screen shot 2015-05-27 at 5 46 00 pm](https://cloud.githubusercontent.com/assets/1957344/7850516/43e071fa-0498-11e5-98ec-81ccffeec28e.png)

Can we also standardize `and` vs. `&`

> Medical Supplies | Medical Supplies & Services
> Office Supplies and furniture | Office supplies and services
>  Planning, architectural, and engineering services | Planning, architecture, and engineering services

**Comment by bsmithgall** [comment]
Work started in e71077a915e5cf621cf79994a746294cf9809a62, need to standardize `and` vs `&` still

**Comment by hamhands** [comment]
Fixed in 21241b6333321fa7261bad55bf824a1431d82063
