### ISSUE TITLE
Bring attention to inactive filter

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#330]
From office hours last week and Dave Osterman's email, I'm getting the sense that people aren't seeing/comprehending the inactive filter. Is there a way to make this more prominent?

**Comment by bsmithgall** [comment]
Isn't this the purpose of the how-to-use documentation?

**Comment by bsmithgall** [comment]
Do we think this has been adequately fixed by the recently merged changes?

**Comment by hamhands** [comment]
@bsmithgall sorry for the late response, but what PR addressed this?

**Comment by bsmithgall** [comment]
https://github.com/codeforamerica/pittsburgh-purchasing-suite/pull/337

**Comment by hamhands** [comment]
the doc + the help text for unsuccessful searches?

**Comment by hamhands** [comment]
I don't have a quick fix for this, but I'm not convinced people see the inactive filter at all, even after seeing the help docs. We should test for this this week maybe.

**Comment by msknee** [comment]
We can make some styling changes to the filters to make them more prominent

**Comment by msknee** [comment]
wontfixing
