### ISSUE TITLE
Stop gap page for see list of vendors

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#331]
The infinite loop for state contracts (see list of vendors) is causing a lot of frustration. Is there any way we could put some kind of helper page that says we're working on this?

**Comment by bsmithgall** [comment]
@hamhands why not just change the name of the company. "See list of vendors" is the company name, which is part of the confusion.

Duplicate of #288

**Comment by hamhands** [comment]
#288 addressed this
