### ISSUE TITLE
Schedule folks for 9/8-9/11

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#333]
Tracking spreadsheet here: https://docs.google.com/spreadsheets/d/1cp9wXFk34zAhngS8FKEBgBJouN9uCFXc0u9Yd96VObc/edit#gid=439284650

**Comment by msknee** [comment]
@hamhands remember to schedule Bonnie tomorrow

**Comment by bsmithgall** [comment]
Is this all finished?

**Comment by hamhands** [comment]
@bsmithgall emailing Bonnie tomorrow and hearing back from Riley.
