### ISSUE TITLE
Add way to unsubscribe from biweekly digest in Manage Subscriptions

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#344]
Currently there's no way to do it.

**Comment by bsmithgall** [comment]
This is going to involve expanding the Vendor model to include some email subscription information.

Other than the biweekly digest email, do we anticipate other emails being sent? I'm trying to figure out the best way to do this.

**Comment by msknee** [comment]
Other nightly (i.e. non-transactional) emails? 

The only other thing I can think of is a 1 or 2 day follow-up to the initial confirmation email, with static content. Just not sure what the content should be.
