### ISSUE TITLE
Change text on Beacon detail page for Download Opportunity Documents

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#347]
Mislabeled IFBs and as a result instructions don't match the name of the file.

![screen shot 2015-09-04 at 3 03 55 pm](https://cloud.githubusercontent.com/assets/1178390/9695479/0a363a7a-5317-11e5-862f-771a5b43230b.png)

**Comment by msknee** [comment]
Copy change, for paragraph following Download Opportunity Documents:

`<p>The documents below contain more detailed instructions about the project timeline, what we're looking for, and how to put together a proposal. We recommend reading documents labeled as an RFP (Request for Proposals), RFQ (Request for Qualifications), Request for Qualified Vendors, or IFB (Invitation for Bid) first, because they have most of the instructions.</p>'

**Comment by bsmithgall** [comment]
@shellicious take a look at these but all of the ones that are on there should be working now. Feel free to close this or change the appropriate text via the admin.

**Comment by msknee** [comment]
Closing this.
