### ISSUE TITLE
Copy/CSS tweaks in Sherpa

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#36]

**Comment by hamhands** [comment]
From @shellicious's doc:
- [ ] /sourcing
  - Move definition of professional services closer to the button (Claire/Janice missed the definition while going through the flow)
- [ ] All end nodes: 
  - create a full-width well for the title, in the style of Beacon opportunities / in the original wireframes
    Remove checkboxes until we build email-checklist functionality

**Comment by msknee** [comment]
Moving this to wontfix / closing this issue.
