### ISSUE TITLE
Invite vendors on Scout to sign up for Beacon

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#361]
- [x] Get emails of vendors on Scout
- [ ] Draft email invitation
- [ ] Send invitation email to them

**Comment by bsmithgall** [comment]
Waiting for me to get emails.

**Comment by bsmithgall** [comment]
Ok, I've finally gotten the emails: https://drive.google.com/open?id=0B7OsELYfuj7vNDdRdy1NcHNWOTQ

@shellicious you should probably go through these manually and make sure that they are all valid emails (they all got imported at once and there might have been problems with that)

**Comment by msknee** [comment]
:+1:

**Comment by msknee** [comment]
Only found 1 error. Will send out the email Monday morning

**Comment by msknee** [comment]
Draft email to vendors: https://docs.google.com/document/d/1mtirh7EkUKf2K9LTMrl1WxN8PaVPe-xb2nq9u4Nk2bs/edit

**Comment by msknee** [comment]
Email sent, ~50 email addresses were no longer in use.
