### ISSUE TITLE
Add contract adoption feedback link?

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#362]
From Bonnie West/Tom Paulin meeting.

As a concession re "I want to be able to search for every contract I can adopt" comment, could we add a form for users to nominate contracts to adopt? This could get sent to someone in OMB to initiate conversation about doing so.

**Comment by bsmithgall** [comment]
Maybe run that feature idea by Riley?

**Comment by hamhands** [comment]
Riley is in favor of this feature. Her one need was for users to explain what the thing is so they could research if there's another contract that would work or not.
