### ISSUE TITLE
Time of day on Beacon

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#365]
From user testing with Ed:

Need to indicate time of day for submission end date. What time of day depends on type of contract. Having a space for actual time of day deadline seems critical.

Example: for inquiries (<$30k), deadline time is 3pm, for formal bids 11:30am (need to confirm this).

**Comment by bsmithgall** [comment]
This is related to #363. In fact, we will need to do that one first to enable this and make sure that there aren't any serious screw-ups because of timezone weirdness.

**Comment by bsmithgall** [comment]
I think a better way to do this might be to have close time as a separate possible field on Beacon maybe with some helper text that can be modified. Having it hard-coded via settings seems tricky, and I'd like to keep everything date-only if possible to avoid weirdness with time zones/daylight savings.

**Comment by hamhands** [comment]
Related to this, the default text of the how do I bid section should be change too: 
<img width="799" alt="screen shot 2015-09-14 at 3 21 47 pm" src="https://cloud.githubusercontent.com/assets/3640800/9859380/4fe71d8e-5af4-11e5-920c-5bdc3ea01045.png">

For example, the EMS billing RFP stops taking submissions at 5pm, not noon.

**Comment by hamhands** [comment]
This is actually probably a larger issue...

"The Proposal packet must include a master copy (so marked) and six (6) copies...". We need default text to be editable I think.
