### ISSUE TITLE
Add spec number to title div of detail page

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#368]
Some contracts have similar names and spec numbers are the way to differentiate. Also, spec numbers starting with 'i' mean they're inquiry (less than 30k) bids, which signals to Ed or Stephanie that they should be bid out a slightly different way (skipping the EORC)

**Comment by bsmithgall** [comment]
Which is better?

![screen shot 2015-09-11 at 10 31 03 am](https://cloud.githubusercontent.com/assets/1957344/9821624/65f9d3b8-5870-11e5-8312-7c9ed0351317.png)
![screen shot 2015-09-11 at 10 32 02 am](https://cloud.githubusercontent.com/assets/1957344/9821625/65fbd640-5870-11e5-85a1-db47286112e5.png)

**Comment by hamhands** [comment]
My vote is on the first option.

**Comment by msknee** [comment]
Agree
