### ISSUE TITLE
Conductor staff can post directly to Beacon from Conductor

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#369]
While OMB is in transition, I don't see great harm in allowing staff with the conductor role to post directly to Beacon about opportunities.

**Comment by bsmithgall** [comment]
Should they have the same dropdown as exist for OMB currently, or should they just automatically publish to beacon @shellicious ?

**Comment by msknee** [comment]
Sliiiiightly in favor of posting to Beacon
