### ISSUE TITLE
Add new view in conductor to manage stages/flows

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#374]
The admin is actually a pretty bad experience.

**Comment by msknee** [comment]
Sketch for UX improvements for ordering stages vertically and adding a new stage to the same box:

![adminstages](https://cloud.githubusercontent.com/assets/1178390/9865542/dd593838-5b25-11e5-8b4b-29a6feb32657.png)

**Comment by msknee** [comment]
@bsmithgall what are the constraints for the admin UI?

**Comment by bsmithgall** [comment]
Many, my hope would be to make this view outside of the admin.
