### ISSUE TITLE
Get conductor ready for launch

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#375]
- [x] Create all stages/flows
- [x] Start all in progress contracts and move them to the appropriate stages.
- [x] Edit the start/stop dates for all in-progress contracts
- [x] Script to clean up all the data
- [x] Clean up all the data

**Comment by bsmithgall** [comment]
Pending done based on some poking around from @shellicious and @hamhands

**Comment by hamhands** [comment]
Did some re-assigning with Ed this morning ([e-waste recycling for example](https://www.buildpgh.com/conductor/contract/2607/stage/1008)), so I think we can call this officially done.

**Comment by bsmithgall** [comment]
Well, we're out the door!
