### ISSUE TITLE
Add default emails

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#381]
Need default email text for all the stages that need them.

**Comment by hamhands** [comment]
Shared with @rileystewart: https://docs.google.com/document/d/1OUfzS29TPMKiMvT1Haf3l0KpLiYniBGNieIrPhSvxl0/edit#

**Comment by hamhands** [comment]
@shellicious did Riley ever get back to you about this?

**Comment by rileystewart** [comment]
Patrick, default emails for now only really need to be for eorc steps, department steps, and the steps after its out for bid where we ask the county the status. Eorc will go to Anthony in the eorc

Riley R. Stewart

**Comment by hamhands** [comment]
@rileystewart :+1:

**Comment by hamhands** [comment]
Emails added to Conductor!

**Comment by hamhands** [comment]
Notes from Ed: we may want to have two versions of the dept review stage, one for the renewal flow, one for the formal bid flow. There are cases where there is no renewal option, so having the default message mentioning renewal might be confusing.

**Comment by bsmithgall** [comment]
This sounds like you should just have two different stages.
