### ISSUE TITLE
Invite Citiparks list to Beacon

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#388]
We're still getting occasional signups on the citiparks site. We should probably kill or update the site directing visitors to Beacon as well as invite the mailchimp list to sign up for Beacon.

**Comment by msknee** [comment]
Thanks for opening this! i am going to make some copy changes

**Comment by hamhands** [comment]
Are you making copy changes to the cleaning site @shellicious? I'd like to get that PR merged today.

**Comment by hamhands** [comment]
(It's [here](https://github.com/codeforamerica/cleaning-pgh/pull/35))
