### ISSUE TITLE
Outline for summit talk

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#391]

**Comment by bsmithgall** [comment]
Notes: https://drive.google.com/open?id=1qooBu4eji4zfrUu5yOt1LDkCo5Feh2tqnBq3wrTCemU

**Comment by msknee** [comment]
Outline / copy: https://docs.google.com/presentation/d/1Z8m2hqQFn9UKi1wd40gFT7_ciUpd-vME2A8lLKz1mYQ/edit#slide=id.g67358522c_0_249
