### ISSUE TITLE
Date issues 

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#411]
Bug surface when reconciling post-wednesday updates with Ed where entered date shows up instead of exit date.

Example in the Final review rec'd from county:
<img width="1207" alt="screen shot 2015-09-21 at 1 44 12 pm" src="https://cloud.githubusercontent.com/assets/3640800/9999903/e8a0e600-6066-11e5-96e6-4cd6cda5aff8.png">

**Comment by bsmithgall** [comment]
I don't understand. Can you be more explicit?

**Comment by hamhands** [comment]
Exit date for final review received is 9/17/2015, not 8/18/15 like it shows above.

**Comment by hamhands** [comment]
This is more of an admin issue. Looks like the activity stream isn't being updated.

**Comment by bsmithgall** [comment]
Oh. Was the spreadsheet wrong then?

**Comment by bsmithgall** [comment]
Oh wait, I think I see what the problem is>

**Comment by hamhands** [comment]
No the spreadsheet wasn't wrong, we're catching up with changes that happened since Wednesday.

**Comment by hamhands** [comment]
I wonder if we should add a way to retroactively complete a step. This is coming up a lot while reconciling with Ed right now, but I can see it being a continuing issue if Stephanie or Ed miss marking complete on a date and need to note that it was completed last week some time.
