### ISSUE TITLE
Item number for in progress contracts

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#416]
Noticed that ed and stephanie both try to search for spec numbers in their in progress contracts. When asked if spec number or item number is preferable for the in progress contracts, Ed said:

> The item number was good to have when we were doing the spreadsheets. When I started sitting in on  the meetings we were having back in the day, they would always shout out spec number 1234 and they would find it on there. Bill was obviously at that point conducting the meetings, so anytime he would  shout out a spec number it was because there was an incident he need to discuss. We would have six pages of spreadsheet you would have to scour through those pages. So I asked if we could add a item number that was consecutive so it was easier to find. Going forward I don’t know if that number would be significant anymore.

So it seems like we should switch to spec number. Thoughts @shellicious @bsmithgall?

**Comment by bsmithgall** [comment]
The main problem with this is that the majority of things in-progress don't actually _have_ spec numbers. They don't get them until the County assigns them.

We could do what we are doing in the title card, which is to display the spec number of the contract if it exists, and if not, display the spec number of the parent contract.

**Comment by bsmithgall** [comment]
Thoughts on this?

**Comment by hamhands** [comment]
@bsmithgall they're just using whatever spec number they have on hand, so I think the same logic that's used in the card would work fine.

**Comment by hamhands** [comment]
The spec number is added for new contracts by the county and only changes when rebids happen. So maybe we could do a '0000' or '9999' or some other kind of designation that indicates this is a new contract, it doesn't have a spec number yet.

**Comment by msknee** [comment]
@hamhands are you saying that we should get rid of the item number column? As long as there's no situation in which it is necessary, that's fine. 

What number should they use to reference contracts instead? The old spec number? The new spec number / "----" if there isn't one yet?

**Comment by hamhands** [comment]
I'm saying that the item number isn't relevant in conductor. It had relevance in a spreadsheet when they needed to scan a paper copy for a record, but in a search interface they use spec number. I haven't seen them try to look something up using the item number, but they try to look up an in progress record using the spec every single time they look up a contract.

**Comment by msknee** [comment]
Ditch item number in favor of spec number.

If no spec number, write "----"
