### ISSUE TITLE
Lost email content

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#417]
Emails keep getting lost in the typical workflow. Usually they only leave the page to open Scout, but if they want to make a note or update metadata, or if they accidentally leave the page or refresh, they lose the content. 

I don't know how we should handle this. Do we put a warning pop up confirming that they want to leave the page, which would lose their content? Is there something more elegant?

**Comment by bsmithgall** [comment]
We could do that, but I guess I'm not sure what you would expect to happen. Building some sort of full-on "draft" feature would be pretty cumbersome and I don't honestly know how much time it would save.

**Comment by msknee** [comment]
@bsmithgall is there a way to preserve the email content when switching between tabs (starting to write an email, and then switching to make a note before the email is done)?

I suggest a warning pop-up when they click on a link that will take them away from the email tab, saying something like:

"Your email changes won't be saved if you leave the email tab. Would you like to navigate away anyway?"

**Comment by bsmithgall** [comment]
Yeah, we could use something like this: https://github.com/codedance/jquery.AreYouSure

**Comment by bsmithgall** [comment]
It doesn't support IE8, though.

**Comment by hamhands** [comment]
Yeah, so Stephanie uses IE exclusively. I think her version is current though.

**Comment by bsmithgall** [comment]
https://github.com/snikch/jquery.dirtyforms
