### ISSUE TITLE
ublock (ad blocker) blocks beacon.js

### ISSUE THREAD

**Issue by ajb** [codeforamerica/pittsburgh-purchasing-suite#422]
A pretty funny bug:

![img](http://take.ms/Y5tPB)

**Comment by bsmithgall** [comment]
Ha! Thanks, I'll rename it to something else.

**Comment by bsmithgall** [comment]
There you go:

https://github.com/chrisaljoudi/uBlock/blob/3e5d6fb8cd3757005ba630c1b332b5cbb6de16bd/assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt#L397-L404
