### ISSUE TITLE
Activity stream confusion

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#424]
Stephanie noted that seeing "started work" on a stage after reverting back could cause confusion. Once they see "started work" on a stage they think it's in that stage, even though it was reverted to a previous one:
<img width="786" alt="screen shot 2015-09-23 at 9 12 47 am" src="https://cloud.githubusercontent.com/assets/3640800/10045811/5d471da4-61d3-11e5-9cc3-598ae2c777bd.png">

I think I agree with her, but I'm not sure how to both note that a reversion happened and that it's no longer in the later step. Thoughts @shellicious @bsmithgall?

**Comment by bsmithgall** [comment]
I'm not sure what the best way to handle this is.

**Comment by msknee** [comment]
Activity stream steps before the "restarted work" step should be light gray, and the blue should be at 50% opacity

**Comment by msknee** [comment]
Change phrasing of start/complete work steps?

"Contract entered _________ on mm/dd/yyyy"
"Step ______ marked complete on mm/dd/yyyy by _____"
