### ISSUE TITLE
Weird email address parsing

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#425]
Stephanie got the email, her CC to herself shows up, but the other cc's she adds (Ed's email address) come back as a bunch of letters separated by commas. Issue comes up when using commas or semicolons as separators in the cc field.
![image](https://cloud.githubusercontent.com/assets/3640800/10046420/abebdd70-61d6-11e5-8c20-5303590499b5.png)

**Comment by bsmithgall** [comment]
Ok this was actually dumb.

**Comment by bsmithgall** [comment]
Fix incoming
