### ISSUE TITLE
Flow UI confusion

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#426]
There's some confusion with the flow pane. Stephanie often stops a step before she needs to because she thinks the step it's currently at has already been complete. 

<img width="1190" alt="screen shot 2015-09-23 at 10 05 59 am" src="https://cloud.githubusercontent.com/assets/3640800/10047168/d207d212-61da-11e5-9266-c4263abed30a.png">

Is there a way we could be explicit that this step is done, this step is waiting for a response, this step is waiting on something from you? Or maybe even a simple checkbox would help?

**Comment by bsmithgall** [comment]
I'm not sure I understand what you mean here.

**Comment by hamhands** [comment]
@bsmithgall just the fact that a step is filled in (aka not greyed out) makes them think the step is done.

**Comment by bsmithgall** [comment]
I still don't understand what you mean. Can you provide a specific, detailed example?

**Comment by hamhands** [comment]
X contract is currently waiting for confirmation that contract is received by the vendor. Stephanie marks complete for every step up to contract sent to vendor. In the contract sent to vendor stage, she should mark complete, but because it's already filled in (even though it's a different color than the completed steps), she doesn't know she should mark complete. So she stops a stage before she should.

What I'm saying is that contracts should only be filled in on the left pane when they've been completed.

**Comment by hamhands** [comment]
Or we should fill them in with a checkmark or something

**Comment by hamhands** [comment]
So in the example in the screenshot, Stephanie thinks renewal request sent to county is completed.

**Comment by msknee** [comment]
Try:

checkmark icon in green circles in left pane, blue outline + white fill in current step circle

ack css

**Comment by bsmithgall** [comment]
![](http://i.imgur.com/Q3cUg29.gif)

**Comment by bsmithgall** [comment]
Still working on the checkboxes

![screen shot 2015-09-23 at 2 44 24 pm](https://cloud.githubusercontent.com/assets/1957344/10059747/a39082cc-6201-11e5-815b-abae5c7e221e.png)

**Comment by bsmithgall** [comment]
![screen shot 2015-09-24 at 10 04 46 am](https://cloud.githubusercontent.com/assets/1957344/10080306/d19f3210-62a3-11e5-8eae-d0bdef2926bf.png)
