### ISSUE TITLE
Contract adoption

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#427]
What is the ideal flow for adopting new contracts? If we add a contract in Scout, it doesn't get added to the contract list in Conductor does it? OMB is the dept that tends to drive adoptions, so they need to be adding it to their tracking procedures right?

**Comment by bsmithgall** [comment]
It should get picked up by Conductor automatically in the "all contracts" assuming it is a county contract. Is there one that isn't being picked up?

**Comment by hamhands** [comment]
Not that I know of, I just want to make sure I understand the connection between conductor and scout.

**Comment by hamhands** [comment]
There have been some dupes in all contracts and that may be why

**Comment by bsmithgall** [comment]
Dupes! Can you attach a screenshot?

**Comment by hamhands** [comment]
@bsmithgall we deleted them...

**Comment by hamhands** [comment]
It was Spec# 6685**

**Comment by msknee** [comment]
Add "adopt contract" button + associated view, form, tests to contract list page

**Comment by bsmithgall** [comment]
This should just take you to a `/new` version of the current `/edit` view in conductor.

**Comment by bsmithgall** [comment]
wontfix after online conversation
