### ISSUE TITLE
Add authorities

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#429]
After Ashbaugh meeting today, we are moving forward folding in authority opportunities.

Laura will take the lead on the organizational portion of this, but for us they asked that we differentiate authorities from city on Beacon. Maybe we need to break up the opportunity layout with prominently displayed logos, etc.

Todo:
- [ ] new layout with opportunities broken up by authority/city
- [ ] put together Beacon internal announcement for week of the 5th
- [ ] do a demo/walkthrough at an OMB event announcing the new procurement policies during our visit, week of the 12th

**Comment by bsmithgall** [comment]
Is it per-authority, or city/authorities?

**Comment by hamhands** [comment]
@bsmithgall is what per-authority etc?

**Comment by bsmithgall** [comment]
There are a bunch of authorities, right? So would it be one section per authority? Or would they all be glommed together?

**Comment by hamhands** [comment]
I think it would be one section per authority. I guess we could do
individual cards per authority maybe?

On Wed, Sep 23, 2015 at 4:56 PM, Ben Smithgall notifications@github.com
wrote:

> There are a bunch of authorities, right? So would it be one section per
> authority? Or would they all be glommed together?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/pittsburgh-purchasing-suite/issues/429#issuecomment-142725836
> .

## 

Patrick Hammons
@hamhandedly

**Comment by hamhands** [comment]
I think for us it's only going to be PWSA and URA. The mayor wants PPA too,
but that's probably phase 2.

On Wed, Sep 23, 2015 at 5:08 PM, Patrick Hammons <
patrick.t.hammons@gmail.com> wrote:

> I think it would be one section per authority. I guess we could do
> individual cards per authority maybe?
> 
> On Wed, Sep 23, 2015 at 4:56 PM, Ben Smithgall notifications@github.com
> wrote:
> 
> > There are a bunch of authorities, right? So would it be one section per
> > authority? Or would they all be glommed together?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/codeforamerica/pittsburgh-purchasing-suite/issues/429#issuecomment-142725836
> > .
> 
> ## 
> 
> Patrick Hammons
> @hamhandedly

## 

Patrick Hammons
@hamhandedly

**Comment by bsmithgall** [comment]
Technical implementation here will be to expand the accepted `CITY_DOMAIN` values to include the authorities.

We should allow this to be configured in the admin maybe?

We need to figure out the domains for:
- [ ] PWSA
- [ ] URA

**Comment by bsmithgall** [comment]
Backend changes
- [ ] Department model migration to add an "external" flag
- [x] New contract type with default text, created via the admin

**Comment by bsmithgall** [comment]
This is in progress as a policy change and appears to be going well
