### ISSUE TITLE
Category dupes

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#431]
This is low priority, but got feedback from SBRF that the category dupes when Select all categories dropdown is selected is annoying when users try to unselect categories. This could be worked around by users, but if it's not a horrible fix it would improve the UX a bit.

Example:
![cats](https://cloud.githubusercontent.com/assets/3640800/10058640/8eaa25d0-6214-11e5-8452-6f2bc536c6c8.gif)

**Comment by bsmithgall** [comment]
@hamhands since the duplicates have different parent categories, they have different IDs. My recommendation here would be to change the displayed values for the select all to have the parent and  child categories both displayed because they aren't actually dupes behind the scenes.

**Comment by hamhands** [comment]
I guess that would be better.

**Comment by hamhands** [comment]
I see what you're saying though.
