### ISSUE TITLE
Print a bunch of flyers

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#435]
People keep asking for Beacon flyers. We should print an absurd amount and leave some in the mayor's office, omb, etc., etc.

Stephanie in particular needs some. She's talking about Beacon at an even in November and asked for handouts.

**Comment by bsmithgall** [comment]
:+1: :+1: :+1: :100: :100: :+1: :rocket: :full_moon:

**Comment by hamhands** [comment]
Also, Laura wants to make merch, like pens and stuff. I think it's a pretty sweet idea.

**Comment by msknee** [comment]
@hamhands do you need the flyer file for printing?

**Comment by hamhands** [comment]
@shellicious no, I have the pdf. I'll send out a job to fedex today.

**Comment by hamhands** [comment]
For future reference, printing 500 flyers costs $195 :money_with_wings:
