### ISSUE TITLE
Conductor --> Scout search indexing

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#442]
Running through renewal for 6689 (PQ CONTRACT FOR WATERPROOFING & ROOFING REPAIRS) process with ED this morning:
- Updated with new contacts and expiration number
- Success message returned
- Contract posted [here](https://www.buildpgh.com/scout/contracts/2615)
- Doesn't show up in search

Does the index get updated daily along with the other jobs?

**Comment by bsmithgall** [comment]
I see it https://www.buildpgh.com/scout/search?q=waterproofing

**Comment by bsmithgall** [comment]
It's not immediate but it looks like it's fine. Would like to close if possible.

**Comment by hamhands** [comment]
We may want to change the language on the update success screen then. Just to say "it may not show up in search yet, but it will soon!". Can't remember if it said something like that or not.
