### ISSUE TITLE
Estimate monthly usage for heroku

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#445]
For t-t-t-t-t-transition

**Comment by bsmithgall** [comment]
Here's my estimation:

2x hobby dyno for web process
1x hobby dyno for worker process
1x hobby dyno for scheduled/nightly tasks
1x hobby basic postgres db
1x hobby Heroku redis
1x SSL endpoint

A bunch of free addons for monitoring/metrics/

thoughts on this?

**Comment by bsmithgall** [comment]
These seem to be pretty good. I will send them over to the Heroku folks tomorrow.

**Comment by msknee** [comment]
:+1:
