### ISSUE TITLE
Display warning message or loading animation while Beacon post is saving

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#450]
While dogfooding Beacon, I've navigated away from the page before the documents have finished uploading, because I didn't notice the % uploaded status in the lower left corner. 

A nice-to-have would be:
- a pop-up that tells me there are unsaved changes (like the one on Conductor)
- or darkening the screen and adding a loading animation that make it really obvious that something is happening on the page, and they shouldn't navigate away

**Comment by bsmithgall** [comment]
Can you add a screenshot/screencap? I can certainly add the `dirtyForms` plugin to Beacon without a ton of trouble, but I'm not totally sure what you mean.

**Comment by bsmithgall** [comment]
Something like this?

![screen shot 2015-09-28 at 4 50 54 pm](https://cloud.githubusercontent.com/assets/1957344/10151878/23644832-6601-11e5-8df8-9b3939842202.png)

**Comment by msknee** [comment]
:+1:
