### ISSUE TITLE
Email apocalypse crisis management

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#453]
Related to #451 
### Mitigation todo:
- [x] respond to direct emails
- [x] check logs for which emails were affected
- [x] draft email noting and apologizing for the issue
- [x] send out email this afternoon
- [x] make mock opp on staging, make sure things are cool

**Comment by bsmithgall** [comment]
Emails: https://drive.google.com/a/codeforamerica.org/file/d/0B7OsELYfuj7vejRWM1lrSWUtQzg/view

**Comment by msknee** [comment]
Draft email: https://docs.google.com/document/d/10XGOVyXmKnTZMRnOEgdFK_l2-IvzEpOr43fQmrUSQZk/edit

feedback pls, @hamhands and @bsmithgall
