### ISSUE TITLE
Digest email bug

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#461]
<img width="704" alt="screen shot 2015-10-01 at 7 17 17 am" src="https://cloud.githubusercontent.com/assets/3640800/10223142/7a7f9ab0-680c-11e5-89f0-55726fcd513d.png">

So that's definitely not true.

**Comment by bsmithgall** [comment]
It came from staging, I turned off the jobs in production -- but yeah.

**Comment by hamhands** [comment]
Oh right! _forehead slap_

**Comment by bsmithgall** [comment]
:+1:

**Comment by hamhands** [comment]
Are you turning jobs in production on soon? Is there a way to send out this digest email again?

**Comment by bsmithgall** [comment]
Let's merge this in first https://github.com/codeforamerica/pittsburgh-purchasing-suite/pull/463
