### ISSUE TITLE
Extending contracts

### ISSUE THREAD

**Issue by dormansteph** [codeforamerica/pittsburgh-purchasing-suite#462]
Good morning everyone,

I extended contract 6459 CONCESSIONAIRE SERVICES but i think i may have extended it twice.  It doesn't tell you in the notes it was extended.  Is that a not we should create ourselves

**Comment by bsmithgall** [comment]
Hi @dormansteph,

Thanks for reporting this!

![](https://i.imgur.com/85f9l0l.gif)

@shellicious what icon should we use to represent the extension in the log?

**Comment by bsmithgall** [comment]
![screen shot 2015-10-06 at 11 47 15 am](https://cloud.githubusercontent.com/assets/1957344/10318796/035fdca2-6c20-11e5-92a9-b2c4973b80f0.png)

**Comment by dormansteph** [comment]
Thank you

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.

**Comment by bsmithgall** [comment]
Great, here's what this will look like

![screen shot 2015-10-06 at 11 55 30 am](https://cloud.githubusercontent.com/assets/1957344/10319066/298ee8a4-6c21-11e5-8ca6-810b63b08057.png)

**Comment by dormansteph** [comment]
perfect!

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.

**Comment by dormansteph** [comment]
Good morning,

SPEC #6459 is still showing in progress "Final Review Received from County" and i extended back on 10/01/15.  I extended it again today not realizing I had sent the issue earlier in the month until now that i am sending it.

**Comment by bsmithgall** [comment]
@dormansteph it won't retroactively show extensions -- it will only show things that have been extended since this change has been made.

As for the current step showing, is this wrong? From discussions early this year it seemed like the extension shouldn't affect the progress of the rebid/renewal. If this is incorrect, please let us know what the proper flow should be.

**Comment by dormansteph** [comment]
i'm not sure let me discuss with Riley.

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.
