### ISSUE TITLE
Messy Beacon data

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#465]
Beacon signup list is pretty messy:
![form](https://cloud.githubusercontent.com/assets/3640800/10262187/96452a7e-6971-11e5-9c0f-743c4c04a0c8.gif)

Is it the validators or the csv parsing causing this?

**Comment by bsmithgall** [comment]
People have commas in the names of their businesses is my guess. We could tab-separate instead of comma-separate here.

**Comment by bsmithgall** [comment]
Also applies to conductor.
