### ISSUE TITLE
Make it easier to input NIGP codes for city staff

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#470]
While adding IFBs to Beacon, I've realized how hard it can be to hunt down the right category. Of the 9 opportunities currently up there, I've had to consult our NIGP code spreadsheet for 2 of them to match the NIGP code listed by the County with our category.  To address this, we could:
- Allow city staff to input the NIGP number. This would solve the issue for IFBs, as the County lists NIGP codes for opps on bidnet.
- more ideas welcome! @hamhands, @bsmithgall?

**Comment by bsmithgall** [comment]
Related to #266

**Comment by msknee** [comment]
I am wontfixing this
