### ISSUE TITLE
ability to click into each contract

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#473]
Some part of the contract line needs to be clickable so that it takes me into the full view of that contract (so I can see dates, steps, notes, etc).  This should not just be an admin feature but everyone should be able to click on any contract to go into it.

**Comment by bsmithgall** [comment]
@rileystewart 

do you see the "update" button on your view? that will let you get into contracts.

![pittsburgh_purchasing_suite_and_codeforamerica_pittsburgh-purchasing-suite](https://cloud.githubusercontent.com/assets/1957344/10321261/930051dc-6c2c-11e5-9263-2ebd5b75412a.png)
