### ISSUE TITLE
User-facing documentation for Pittsburgh Procurement Suite

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#482]
Walkthrough for admin level users: @shellicious covering this section

https://docs.google.com/document/d/1fjPSmQxTxIkvcOT5RjtG69_oRFDoZGdOdcbQd85C3aI/edit#heading=h.tiw5v5khzivs

**Comment by bsmithgall** [comment]
It would be really good to get some thoughts here from @cydharrell

**Comment by bsmithgall** [comment]
@shellicious @hamhands can you put links to all the documents in here? I'm going to re-organize the README a little bit today/tomorrow and would love to have links to everything.

**Comment by hamhands** [comment]
@bsmithgall direct download pdf or google doc?

**Comment by bsmithgall** [comment]
Doc would be better

**Comment by hamhands** [comment]
- [Conductor walkthrough](https://docs.google.com/a/codeforamerica.org/document/d/1gJa8RzbiV91UDNyRTBLGXmZIYuXtnY8BOK6VNyCbqSg/edit?usp=sharing)
- [Scout walkthrough](https://docs.google.com/document/d/1hV5_yHKWWgU2qgtPI011cdiWOvXewRJK3v-MaXEXEkA/edit?usp=sharing)
- [Beacon walkthrough](https://docs.google.com/document/d/1z2ujIVJ0pa0lN9rO_1W3MrLTUe_smpwrWyXpWZEVp4Q/edit?usp=sharing)
- [Admin walkthrough](https://docs.google.com/document/d/1fjPSmQxTxIkvcOT5RjtG69_oRFDoZGdOdcbQd85C3aI/edit?usp=sharing)
- [End of Year Report](https://docs.google.com/presentation/d/1Rw_nMTUQTbFxnq9x-uQIPGC0IdnwdWPB2yHVAY1mG0g/edit?usp=sharing)

**Comment by bsmithgall** [comment]
Can we get a link to the end-of-year report here as well?

**Comment by msknee** [comment]
added!
