### ISSUE TITLE
First step of Conductor contracts can't be back-dated

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#491]
Options:
- Can specify date in the past when starting work on a contract
- Go through data and manually set date to something in the past

@dormansteph brought this to our attention! Do add a spec # or item # of the contracts you're having trouble with, Steph, in the comments below

**Comment by dormansteph** [comment]
can you update Item 2107 Street Lighting Services (CD Areas) the expiration date should be 6/30/2016 everything else is good.

**Comment by bsmithgall** [comment]
@dormansteph Riley should be able to do that for you -- sorry I didn't see this until now!
