### ISSUE TITLE
Special requirements for I&P

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#5]
Riley commented that to buy technology, there are further I&P requirements that should be implemented in Sherpa or the checklist.

**Comment by bsmithgall** [comment]
This should be pretty simple to accommodate -- just have a separate filter Y/N for technology contracts and two termination nodes.

**Comment by hamhands** [comment]
I think this issue is more complicated than just more nodes. We need typeforms for all contracts, including Letters of Authorization (contractor project contracts), Work Orders (professional service project contracts), and Piggybacking contracts. Working to get full universe from legal or whoever has that knowledge.

**Comment by bsmithgall** [comment]
I think it's probably both.
