### ISSUE TITLE
Filters & Sorting

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#50]
- [x] Filtered searching by line items, company, contract description, etc
- [x] Column sort

**Comment by bsmithgall** [comment]
@hamhands Great. Can you add any other frustrations that were available and maybe we can brainstorm possible solutions?

**Comment by hamhands** [comment]
_Searches for SHI_
- "Ok what did it do. Did it give me everything that has SHI?"
- "I don’t know why I got this."
- Washing, Toshiba

_Searches for dell_
- "That’s good, but can I narrow it down even further? In that I’m looking for a vendor named dell?"
- "How would I find something that hasn’t been adopted yet? Is there a way to ask the purchasing department to adopt a state contract?"

_Searches for software_ 
- "Costars 3 is a hardware contract I don’t know why it says equipment and software"

_Searches cables_
- no results
- "I’m not having a lot of luck here!"

_Searches wires_
- "Looks like a construction contract…"
- "Where would I see [my search term]? Would it be highlighted somewhere?"

_Searches wire_
- "I got a lot more results!"

_Searches cable_
- "Huh!"
- "Maybe more specific..."

_Searches computer cable_
- "I’m not getting any of our vendors"

_Searches eplus_
- nothing
- "I know we use them all the time"

_Clicks on SBM_
- "Would there be more information here?"
- "It’s nice to know they’re on costars 6, but it would be even nicer if I knew what software they offer"
- "This is very nice"
- "To get this far on the costars contract is very tedious"

**Comment by hamhands** [comment]
"How do I know which of these vendors can supply Knowledge Lake?"
- "In the past we have had knowledgelake from Dell"
- "Even if it’s not on there anymore, we used to be able to get it, how would we be able to find that?"
- Expired or formerly held contracts

**Comment by bsmithgall** [comment]
@hamhands "What software they offer" is categorized under "Manufacturers." What would a better way of handling that be?

**Comment by hamhands** [comment]
@bsmithgall I think manufacturers makes the most sense, but routing searches to that field is probably the main issue.

**Comment by hamhands** [comment]
Perhaps highlighting search results in page would help. She didn't know about ctrl + F.

**Comment by bsmithgall** [comment]
This is related to, but different from #56.
