### ISSUE TITLE
Can filter in-progress contracts by expiration date 

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#500]
Jennifer and purchasing agents would like to be able to prioritize work on in progress contracts. One of the ways they do it is by looking at the expiration date.

**Comment by bsmithgall** [comment]
![screen shot 2015-10-14 at 12 05 42 pm](https://cloud.githubusercontent.com/assets/1957344/10489732/37692f88-726c-11e5-80e6-020797714cf2.png)
![screen shot 2015-10-14 at 12 05 33 pm](https://cloud.githubusercontent.com/assets/1957344/10489733/37699f54-726c-11e5-840e-7cb668ce8552.png)
