### ISSUE TITLE
Expiration date + old spec # in Conductor detail view easier to read, add new spec #

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#503]
Stephanie associates light gray text with inactive / not relevant information. 

Try making the expiration date and spec number black, or highlighting it with red / yellow according to the same rules as how color is displayed on the contract list page.

**Comment by msknee** [comment]
Update from Ed:

He'd like to see the new spec # on a separate line, underneath the old spec #. It can say "----" if there isn't one yet. When he updates the metadata with a new spec, he wants it to update in the header area.

**Comment by bsmithgall** [comment]
@shellicious I feel like we can use this space a bit better.

![screen shot 2015-10-14 at 8 29 32 pm](https://cloud.githubusercontent.com/assets/1957344/10501738/69df2468-72b2-11e5-8f96-4359984bd2c2.png)
