### ISSUE TITLE
Ability to delete opps from pending page

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#518]
Seeing duplicates of opportunities that have already been published, and published and closed:

![pending_licecap](https://cloud.githubusercontent.com/assets/1178390/10591215/e077762e-7669-11e5-8b49-02fa658fff4e.gif)

I suggest:
- Adding delete button next to the edit button to remove duplicates
- Showing the email address of the person who added the post on the card, so they can be contacted to figure out why there are duplicates.

**Comment by hamhands** [comment]
Preferences @shellicious?

### Option 1:

<img width="1178" alt="screen shot 2015-10-20 at 11 16 11 am" src="https://cloud.githubusercontent.com/assets/3640800/10617019/07a47dd8-771d-11e5-8092-6b5ec75a41c8.png">

### Option 2:

<img width="1160" alt="screen shot 2015-10-20 at 11 22 45 am" src="https://cloud.githubusercontent.com/assets/3640800/10617006/f37c75fe-771c-11e5-8cc3-1199c498e0cc.png">
