### ISSUE TITLE
Investigate costars/state contracts

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#527]
Need to determine the overlap and deviation of costars and state contracts.

**Comment by msknee** [comment]
I called the state procurement office at (717) 787-5733, and was transferred to the COSTARS help desk. I spoke with someone there that told me state contracts and COSTARS contracts are different: a supplier can have a state contract with certain terms, and also be on a COSTARS contract with different terms. Cities can use COSTARS contracts if they are "COSTARS members", and also piggyback off of state contracts.
