### ISSUE TITLE
backdating steps on conductor doesn't work right

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#529]
I was working in contract A-083-14 to change the date it was started to a few days earlier than when we originally marked it.  I went in and hit the mark complete button and the box keeps opening and closing making it nearly impossible to actually type in a date. 

After I finally got it completed, it made the 'step complete in -22 hours' which is very odd.

**Comment by bsmithgall** [comment]
Working on this now.
