### ISSUE TITLE
Modify email promotion links for Beacon (opps site) based on mailing list audience

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#53]
@davidrleonard suggested appending identifiers to promotional links, so that we can track conversion by mailing list (main street managers, EORC, etc.). 

To-do's:
- [x] clarify what this means. @davidrleonard, can you direct us to a helpful link that explains this?
- [x] Set it up for Henry's list and Kevin's list

**Comment by davidrleonard** [comment]
Here's a way to "build" source links from Google Analytics documentation:
https://support.google.com/analytics/answer/1033867?hl=en

Generally, here's what you want to know: How did this person who did an
action get to my site? Are people coming from a certain place doing this
action way more -- how can I determine why/why not, and make my site better?

Example: You send an email to Women Business Org members to sign up for
your list. You send them this url:
http://pitt-email-app-url.com/signup?utm_source=womenBizOrg&utm_medium=email

Google Analaytics read this all and determines your user came from the
"womenBizOrg" email, and let's you filter your data based on that. You can
then draw insights about how users from the Women Business Organization
understand and interact with your content, and ensure you're serving them
appropriately.

Just pass a new utm_source= parameter for each email, and watch the data
get specific and fancy.

David Leonard
Code for America
p: 951-691-7772
e: dleonard@codeforamerica.org

**Comment by msknee** [comment]
URLs! (DON'T CLICK)

http://pittsburgh-purchasing.herokuapp.com/beacon/?utm_source=mainstmanagers&utm_medium=email&utm_campaign=beaconsoftlaunch

http://pittsburgh-purchasing.herokuapp.com/beacon/?utm_source=eorc&utm_medium=email&utm_campaign=beaconsoftlaunch

**Comment by msknee** [comment]
For reference, analytics will show up in GA under Acquistion --> Campaigns --> Source tab

![screen shot 2015-07-30 at 10 56 17 am](https://cloud.githubusercontent.com/assets/1178390/8990844/b2fdb1e0-36a9-11e5-9938-2570b28f1859.png)
