### ISSUE TITLE
Contract title showing up wrong in conductor

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#530]
A-072-15 is labeled in Scout as 'Printing and....'  and the check box is checked to show in conductor. 

It is not showing in conductor.  There is however a spec by that number showing with the label 'bookbinding' (this should be labeled printing just like it is in scout)

**Comment by bsmithgall** [comment]
Will look into this today.

**Comment by bsmithgall** [comment]
Also PQ contract for printing services (controller #49573, id #2313)

**Comment by bsmithgall** [comment]
This should show up now.

**Comment by bsmithgall** [comment]
@rileystewart if there is another problem with a contract that has a controller # that isn't #49573, please let me know.
