### ISSUE TITLE
Bulk-add Riley to followers for all non-conductor non-expired contracts

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#531]

**Comment by bsmithgall** [comment]
@rileystewart -- before I push go on this, I want to confirm that you want to bulk-follow all **non-conductor** contracts, which means everything that isn't County, A-Bid, or B-Bid type.

**Comment by rileystewart** [comment]
Correct

Riley R. Stewart

**Comment by bsmithgall** [comment]
@rileystewart you are now following 2,214 contracts.

![screen shot 2015-10-28 at 10 57 38 am](https://cloud.githubusercontent.com/assets/1957344/10798018/b9380862-7d62-11e5-9a1f-d862c70d2801.png)
