### ISSUE TITLE
Write copy + Beacon button for omb contracts site

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#532]
The OMB contracts site should display a message directing visitors to Beacon, and have a banner or large button to call attention to Beacon. The banner/button could also be reused on other pittsburghpa.gov pages.

**Comment by msknee** [comment]
Banner for main content block is complete. Next:
- [x] Get procurement team approval
- [x] Design sidebar banner
- [x] Email web team and send them assets

**Comment by msknee** [comment]
Proposed changes:

![omb-mainpage](https://cloud.githubusercontent.com/assets/1178390/10896841/973c0fca-818a-11e5-8104-71334121a020.png)

![omb-contractspage](https://cloud.githubusercontent.com/assets/1178390/10896844/9741c26c-818a-11e5-9fe9-18151a02d101.png)

Banners:

![beacon_ombpage-banner-large](https://cloud.githubusercontent.com/assets/1178390/10896842/973ca89a-818a-11e5-90bd-f5365780a368.png)

![beacon_banner-small](https://cloud.githubusercontent.com/assets/1178390/10896843/973cc398-818a-11e5-8de9-fbd7435aafa7.png)

**Comment by bsmithgall** [comment]
:+1: :100: 

can we make the yellow part of the bottom one into a sticker?

**Comment by msknee** [comment]
GOOD IDEA @bsmithgall

**Comment by msknee** [comment]
Emailed @laurameixell assets + proposed changes, will close when we hear back about the ticket

**Comment by msknee** [comment]
:smiley:
