### ISSUE TITLE
Back Date

### ISSUE THREAD

**Issue by dormansteph** [codeforamerica/pittsburgh-purchasing-suite#539]
I'm trying to update SPEC #7384 it was started on Sept 3 and i'm trying to continue with that date and i'm getting an error message saying the date conflicts replaced with today's date

**Comment by dormansteph** [comment]
date field is not working at all to update in conductor

**Comment by rileystewart** [comment]
The date box should prepopulate with today's date.  Also it would be nice if a calendar popped up similar to how it does in Admin:Scout:Contracts

The format of the date is confusing with the year, month, day when then it is displaying month, day, year (aka 10/23/15).  Also we would prefer if we didn't have to put in a specific hour/minute as that really doesn't matter.

**Comment by bsmithgall** [comment]
Hour/minute is important if we want to have accurate metrics. 

The calendar timepicker should pop up now. 

@dormansteph a conflicting date error message will show up if you try to backdate before the start date for that stage, including the time.

**Comment by dormansteph** [comment]
Its not popping up and I still can't enter a back date or any date.  I'm
trying to update SPEC #7384

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.

**Comment by bsmithgall** [comment]
I'll look into it right now.

**Comment by bsmithgall** [comment]
@dormansteph I've patched this problem and will let you know here when it is live -- it should hopefully resolve the problem. If it does, feel free to close the issue. If not, I'll continue working on it.

**Comment by bsmithgall** [comment]
Ok, it should be live, please try again!

**Comment by dormansteph** [comment]
The calendar appears but it doesn't let you back date

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.

**Comment by bsmithgall** [comment]
You can't backdate a step with a completion date that is earlier than that start date for the step. It looks like you started that step today, so I'm not sure this is wrong.

**Comment by dormansteph** [comment]
I was trying to back date it for 09/03/2015 and it populated today's date
saying there is a discrepancy in the date.  It was sent to city review
09/03/2015 returned from city review 9/03/2015 and I want to make the
county review 9/03/2015 and county return 9/03/2015

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.

**Comment by bsmithgall** [comment]
Ok, I think this is a different need then -- you need to be able to restart a stage in the past. This is a new feature, so I'm going to close this issue and make a new one that captures that work.

**Comment by dormansteph** [comment]
Good morning,

I was trying to back date a work started (very first step) SPEC #7197 for november 10th and it would not allow

**Comment by bsmithgall** [comment]
Hi @dormansteph !

I'm looking into this. When #599 gets merged and deployed, you will be able to do this more easily: check out the screencap below for more information

![autom8](https://cloud.githubusercontent.com/assets/1957344/11154750/473e07a2-8a0f-11e5-87f9-f3b87181faf3.gif)
