### ISSUE TITLE
Contract disappeared from Conductor

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#549]
Stephanie was working on updating a contract for Ballfields.  It gave her an error message and now the contract is gone from Conductor.  I searched in scout and there is still a contract that looks like they do when one is being worked on in conductore (i.e. empty controller empty expiration).

**Comment by bsmithgall** [comment]
@dormansteph could you put here the steps that you were doing so that I can try to reproduce this error?  It's not totally clear what happened from the logs.

**Comment by dormansteph** [comment]
SPEC 7438 was in the all contracts section
clicked on actions
start work
and it brought a box up
i clicked in the date box to see if it would work
didn't change the date from today
and it start
the error message said
oops something went wrong don't panic we are fixing it 500

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.

**Comment by bsmithgall** [comment]
Hmm that is definitely unexpected behaviour. I'll look into it more today.

**Comment by bsmithgall** [comment]
I think the solution involves refactoring the batch create process out into next step creation during the contract transition. For this contract, is it ok if I just reset it to the way it was?

**Comment by bsmithgall** [comment]
@dormansteph I reset it, could you try to re-assign the contract?

**Comment by dormansteph** [comment]
do i need to enter the contract as new.  it's gone.

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.

**Comment by bsmithgall** [comment]
Yes, you will need to restart it -- I reset it to before work on that one was started.

**Comment by dormansteph** [comment]
Its gone.  I cant restart i will need to renter the SPEC correct?  Where
did it go.

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.

**Comment by bsmithgall** [comment]
You'll need to restart it from the all contracts section:

![screen shot 2015-10-27 at 10 02 00 am](https://cloud.githubusercontent.com/assets/1957344/10765808/d27f6634-7c91-11e5-9a72-03f01b96e062.png)

**Comment by msknee** [comment]
Has this been resolved?

**Comment by dormansteph** [comment]
yes

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.

**Comment by bsmithgall** [comment]
Thanks for reporting and following up @dormansteph !

**Comment by dormansteph** [comment]
you're welcome

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.
