### ISSUE TITLE
post to beacon from conductor is not popping up

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#554]
![image](https://cloud.githubusercontent.com/assets/12427992/10794571/e0a74b48-7d6b-11e5-9ca6-f853b8a14298.png)

trying with spec 6459 and it won't pop up.  also, it highlights all of the filters if you're trying to change between the filters....i'm guessing its supposed to switch from one to another

**Comment by msknee** [comment]
@rileystewart it works from the "Final Review Approval Sent to County" stage, which is not the one this contract is currently in. 

You can go here in the admin (https://www.buildpgh.com/admin/stage/) to add Beacon posting capability to any stages, by clicking on the pencil icon and selecting the "Post Opportunities" check box.

Here's a screenshot of all the stages that currently have the Beacon posting capability:

![screen shot 2015-10-28 at 9 54 08 am](https://cloud.githubusercontent.com/assets/1178390/10796119/f91a5e34-7d59-11e5-857c-7b7f94d7e0ca.png)

**Comment by rileystewart** [comment]
it should work from multiple steps.  at that step we would never know when it was going to be posted/finished and we would not have the final copy of the RFP in the county format.

it should work from final review sent to county and bid posted.

**Comment by msknee** [comment]
@rileystewart check out the screenshot: it does work from "final review approval sent to county" and "bid posted". As an admin, you can add the post-to-Beacon functionality from the URL I shared above if you'd like it to work from more stages.
