### ISSUE TITLE
download all suppliers from beacon

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#555]
I was assuming that this option would download into a readable format like excel.  I have clicked it and it goes into a huge Notepad download with no separations.

This should be in a readable format so we can filter/send off addresses of vendors that have the category we are looking for.

**Comment by bsmithgall** [comment]
It's a tab-separated file, which you can open with Excel.

**Comment by rileystewart** [comment]
it doesn't give me an option. it just automatically downloads it in notepad format

**Comment by bsmithgall** [comment]
https://support.office.com/en-us/article/Import-or-export-text-txt-or-csv-files-e8ab9ff3-be8d-43f1-9d52-b5e8a008ba5c#bmimport_data_from_a_text_file_by_openi

**Comment by msknee** [comment]
Try this? https://www.youtube.com/watch?v=OriqzXqLcaw
