### ISSUE TITLE
NIGP codes on conductor

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#558]
- [ ] Get time with Jennifer and ask her what code input and output she prefers
- [ ] Add field for NIGP codes to "Add a contract" and/or admin
- [ ] Show NIGP codes by clicking + button in Conductor contract list

**Comment by msknee** [comment]
Meeting scheduled with Jennifer and Riley Wednesday 11/4

**Comment by msknee** [comment]
I am wontfixing this

**Comment by bsmithgall** [comment]
:+1:
