### ISSUE TITLE
Unsuck Search

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#56]
Elasticsearch? Postgres fulltext?

Let's do some research.

**Comment by bsmithgall** [comment]
http://blog.lostpropertyhq.com/postgres-full-text-search-is-good-enough/

**Comment by bsmithgall** [comment]
Let's go with full text search for now. @ondrae do you think you could take a look at the code when I get a chance to make changes?

**Comment by bsmithgall** [comment]
From #50 

_Searches for SHI_
- "Ok what did it do. Did it give me everything that has SHI?"
- "I don’t know why I got this."
- Washing, Toshiba

_Searches for dell_
- "That’s good, but can I narrow it down even further? In that I’m looking for a vendor named dell?"
- "How would I find something that hasn’t been adopted yet? Is there a way to ask the purchasing department to adopt a state contract?"

_Searches for software_ 
- "Costars 3 is a hardware contract I don’t know why it says equipment and software"

_Searches cables_
- no results
- "I’m not having a lot of luck here!"

_Searches wires_
- "Looks like a construction contract…"
- "Where would I see [my search term]? Would it be highlighted somewhere?"

_Searches wire_
- "I got a lot more results!"

_Searches cable_
- "Huh!"
- "Maybe more specific..."

_Searches computer cable_
- "I’m not getting any of our vendors"

_Searches eplus_
- nothing
- "I know we use them all the time"

_Clicks on SBM_
- "Would there be more information here?"
- "It’s nice to know they’re on costars 6, but it would be even nicer if I knew what software they offer"
- "This is very nice"
- "To get this far on the costars contract is very tedious"
