### ISSUE TITLE
Get all costars vendors servicing Allegheny county

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#57]
For COSTARS 3 and possibly others, the data we have has been filtered by Allegheny and the surrounding counties. The total vendors servicing Allegheny county on COSTARS 3 is 181, while we only have 22.
### Screencap of how to get to costars search

![costars](https://cloud.githubusercontent.com/assets/3640800/8012093/7b651acc-0b8c-11e5-821a-0db0cb847ee7.gif)

**Comment by bsmithgall** [comment]
Steps:
1. http://www.dgs.pa.gov/Local%20Government%20and%20Schools/costars/Pages/default.aspx#.VXHt3GRViko
2. Click on "Learn more about COSTARS participation for Member entities"
3. Click on "Search the list of current COSTARS contracts"
4. Click on "Search contracts" from the left nav pull-out. Note that you cannot navigate to this page directly.

**Comment by hamhands** [comment]
Get the total contracts serving Allegheny county, subtract what we have from that total.

**Comment by hamhands** [comment]
![screen shot 2015-06-12 at 1 46 30 pm](https://cloud.githubusercontent.com/assets/3640800/8139561/8cf12b78-1109-11e5-8d77-c4ea70dac87d.png)

1065 costars contracts serving Allegheny county, I'm showing 216 on local wex. So 849 contracts we don't have yet?

**Comment by hamhands** [comment]
@bsmithgall @shellicious I think the above answers our questions re the order of how many contracts we're missing. Are we blocked on anything else?

**Comment by bsmithgall** [comment]
Yeah what's the plan?

**Comment by msknee** [comment]
@bsmithgall @hamhands how long will it take to download 849 contracts? A very tedious 2 hours? Separately, how long will it take to parse 849 contracts? A week?

**Comment by bsmithgall** [comment]
No idea.

**Comment by hamhands** [comment]
![screen shot 2015-06-15 at 10 39 39 am](https://cloud.githubusercontent.com/assets/3640800/8166148/d6bf67fe-134a-11e5-9efd-42d52475b050.png)
Ooh, now it's 1068

**Comment by hamhands** [comment]
Downloading each contract is pretty quick, could probably be done in an hour or so.

The main issue is that there isn't a way to sort/filter by date contracts are adopted. Everything is sorted by vendor name, which doesn't help us. We'll have to compare vendor contract numbers every time we update the data.

**Comment by bsmithgall** [comment]
Can you be more explicit about what you mean by this?

**Comment by hamhands** [comment]
@bsmithgall which part? The downloading or the lack of a date added option in the costars search?

**Comment by bsmithgall** [comment]
I guess I'm unclear about what you mean when you say "every time we update the data" -- what is being updated?

**Comment by hamhands** [comment]
New contracts are added on the costars site

**Comment by hamhands** [comment]
When I looked Friday there were 1065 contracts servicing allegheny county. Three have been added since then.
