### ISSUE TITLE
Back Dating

### ISSUE THREAD

**Issue by dormansteph** [codeforamerica/pittsburgh-purchasing-suite#571]
If you change the flow of the contract it changes the date.  We need to be able to back date on the change of the flow

**Comment by bsmithgall** [comment]
Hi Stephanie,

Reverting the flow should take you step 1 of the new flow, which should allow you to go to back to the "start" screen and rewind the open time. This should have the same effect. Does this work?

**Comment by dormansteph** [comment]
No it doesn't.  This isn't the first time I've done it.  It was SPEC 7164

Kind Regards,

Stephanie M. Dorman
Procurement Coordinator
414 Grant Street
Room 502 City-County Building
Pittsburgh, PA 15219
Phone: (412) 255-2485
Fax: (412) 255-2367
Email: stephanie.dorman@pittsburghpa.gov

The City of Pittsburgh has launched a new opportunity site called BEACON!
Please visit  https://www.buildpgh.com/beacon/ and register for news about
upcoming opportunities.

**Comment by bsmithgall** [comment]
I see. In the future when you switch flows, you should be able to do it
this way. I can add this feature to the current backlog, but I am not sure
we will be able to get to it. You might bring this up and we can think
about prioritizing it against other features.

For now, you can revert to the first stage of the flow, change the start
date, and then fill in from there.

**Comment by bsmithgall** [comment]
Closed via offline conversation in procurement meeting
