### ISSUE TITLE
Beacon still throwing 500s with weird rquot characters

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#578]

**Comment by bsmithgall** [comment]
Not in the logs though.

**Comment by bsmithgall** [comment]
@hamhands can you see if you can repro this?

**Comment by hamhands** [comment]
@bsmithgall :+1:

**Comment by hamhands** [comment]
Can't reproduce this error so it looks like this was in fact fixed in #525. Will email Jennifer.
