### ISSUE TITLE
can't get contract to appear on conductor

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#592]
Stephanie accidentally decided to remove a contract from conductor.  When I go to scout and find the contract, the check mark is still checked for conductor though.  I need that contract to go back in conductor but can't get it to appear back.

spec 7096.

It seems like the 'visible on conductor' box in Admin:Scout means nothing and is controlling nothing.

**Comment by bsmithgall** [comment]
Which do you want? Do you want to undo the removal and have the child contract back into the "Department Review Sent?" If so, you can go [here](https://www.buildpgh.com/admin/conductor-contract/edit/?url=%2Fadmin%2Fconductor-contract%2F%3Fsearch%3Dcity%2Bvehicles&id=2619) and un-archive that child contract.

If you want, I can also delete that contract and you'll be able to start over from the beginning.

**Comment by bsmithgall** [comment]
I've made some changes to the admin to make this a bit easier to deal with -- I'll push them up and merge them. You'll need to use the Admin/Conductor/Contract bit to get it to work. Here's what it will look like:

![autom8](https://cloud.githubusercontent.com/assets/1957344/11083902/b77a3112-8802-11e5-981a-dbaea24af10d.gif)
