### ISSUE TITLE
Admins can make other users admins

### ISSUE THREAD

**Issue by msknee** [codeforamerica/pittsburgh-purchasing-suite#600]
![screen shot 2015-11-12 at 3 36 19 pm](https://cloud.githubusercontent.com/assets/1178390/11134889/3493fdce-8955-11e5-94a9-9f24f640313e.png)

From Users (https://www.buildpgh.com/admin/user/), superadmins can't make other users admins. 

From Users w/Roles (https://www.buildpgh.com/admin/user-roles/), superadmins can make other users admins. Is this a bug?

Not sure what an admin can/can't do from either page.

**Comment by bsmithgall** [comment]
This is fixed by a recent deploy
