### ISSUE TITLE
If you start a spec number, the rest of the spec numbers should disappear from conductor

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#602]
The second that you start working on a particular spec number, the rest of the contracts with that same spec number should disappear.

**Comment by bsmithgall** [comment]
Hi @rileystewart, this will depend on the controller numbers/vendors, as we talked about on the call last week. We settled on manually removing it and trying to collapse the different contracts into one in the future.
