### ISSUE TITLE
conductor isn't reflecting what is in admin

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#603]
I'm looking on conductor all contracts at spec 6682.  There are 2 vendors w/ different spec numbers that should appear under all contracts.  It is displaying 6682 twice but w/ the vendor twice instead of each vendor once with their respective controller numbers

**Comment by bsmithgall** [comment]
I'll look into this today.

**Comment by bsmithgall** [comment]
It looks those are duplicates. One of them went through the full renewal process (Item Number: 2611, which is a child of Item Number 2605). Basically those two are duplicates. If the other company is still on the contract, I would add it to item number 2611 ([https://www.buildpgh.com/admin/contract/edit/?id=2611](here's a link to the admin page for that one)), and remove the other one from use in the all contracts page.
