### ISSUE TITLE
COSTARS data entry page for Riley

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#61]
This should do the following:
- List all COSTARS contracts by COSTARS number
- Basic data entry form:
  - COSTARS basic metadata
  - Some sort of way of handling variable numbers of line items, manufacturers, etc.

Let me know what you think @rileystewart

**Comment by hamhands** [comment]
- [x] new form
- [x] new view 
- [x] new template
- [x] line items (tricky)
