### ISSUE TITLE
Sort/Color by Expiration date does not work in conductor

### ISSUE THREAD

**Issue by rileystewart** [codeforamerica/pittsburgh-purchasing-suite#616]
I am trying to sort by expiration date to see the contracts that expired the longest time ago.  This is not working.  Also I believe the color coding for the expiration date column was supposed to be based on if the contract was expired (aka if the contract has already expired it's red, if its within 90 days of expiration it's yellow).  Currently it is just whatever color the 'Current Step Started' is in

**Comment by bsmithgall** [comment]
Fixed by https://github.com/CityofPittsburgh/pittsburgh-purchasing-suite/pull/3

@rileystewart you can open issues over there now as well

**Comment by bsmithgall** [comment]
As for the colors, this was the design decision reached a long time ago when we were first doing the conductor mockups. It can be changed, but it would be good to make sure that that is in line with what Ed & @dormansteph need.
