### ISSUE TITLE
Form to add opportunities to Beacon

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#63]
Features to implement:
- [x] Form on the backend to create new opportunities
- [x] View on frontend for listing and details for opportunities
- [ ] Sign up for notifications on specific contracts

Things we need to think about:
- How do we send notifications? Automatically? If so, what are the triggers? What is the content for the notifications?

**Comment by msknee** [comment]
Wireframe of opportunities listing:

It's missing an "edit" link -- we could swap in "edit" links for the selection boxes on the left, which no one used during user testing.

![opportunities-04](https://cloud.githubusercontent.com/assets/1178390/8385501/6da7a428-1c16-11e5-838f-49ce9beed60c.png)
