### ISSUE TITLE
Form to upload CSVs of all COSTARS contracts

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#66]
Related to #61

**Comment by hamhands** [comment]
### Properties:
- [ ] COSTARS Group (Costars 1, 2, 3, etc)
- [ ] Is adopted?

**Comment by bsmithgall** [comment]
Is this closed now @hamhands ?

**Comment by hamhands** [comment]
Currently testing locally, having some issues. 

@bsmithgall after fixing the header issue, page is getting hung up. Logs only returning 200, not further information. We should triage tomorrow morning.
