### ISSUE TITLE
Where does forms go?

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#7]
Concern in legal about storing legal documents and contracts on an external server.

**Comment by bsmithgall** [comment]
Hm this is an interesting point. I have no idea how easy/hard it would be to have this read files from, say, internal servers. I'm also wondering what the actual concern is about:
- We aren't actually storing any finalized documents, only blank ones/templates.
- Finalized documents _are_ already stored on an external server (Onbase)

**Comment by bsmithgall** [comment]
TODO: Reassure them that typeform is safe. (Talk to tech team/Laura about this).

**Comment by hamhands** [comment]
Issues resolved, given approval by I&P Deputy Director of Operations. [Privacy policy](https://admin.typeform.com/to/dwk6gt) forwarded to law dept.
