### ISSUE TITLE
Atlas endpoints need content

### ISSUE THREAD

**Issue by hamhands** [codeforamerica/pittsburgh-purchasing-suite#81]
From @shellicious's google doc:
- [ ] /wallace-act-professional-services: Wallace Act
- [ ] /sole-source-r-f-p: Sole Source
- [ ] /phone-quote-single-use: Phone quote for goods/services from $2k - $29,999
- [ ] /department-sole-source-r-f-p: RFP for professional services above $30k
  - Add Slim’s RFP template
- [ ] /county-r-f-p-process: County IFB process
- [ ] /explanatory: Explanatory
  - Add explanatory forms
- [ ] /use-it: 
  - [ ] Everyone is confused by the text here. This should say something like, “If you’re sure the item you want is sold by a business that’s on contract with the city, follow these steps to make the purchase: ______”. 
  - [ ] And a link that opens Scout in a new tab, so they can confirm their assumptions.
- [ ] /construction: how many kinds of construction contracts are there?

**Comment by bsmithgall** [comment]
@hamhands we talked with Riley this morning and she said that she was interested in getting started on writing some of the content. You should take a look at the draft form that @shellicious put together with all of that information.

**Comment by bsmithgall** [comment]
Another task to be added here is the actual renaming of Sherpa --> Atlas.

**Comment by hamhands** [comment]
What should we do with this @bsmithgall @shellicious? Wontfix?

**Comment by bsmithgall** [comment]
Are we actually killing off Atlas? That seems to have happened quickly.

**Comment by hamhands** [comment]
I don't think we're killing it off. What do we do with issues for products
moved to the back burner?

On Mon, Aug 17, 2015 at 11:55 AM, Ben Smithgall notifications@github.com
wrote:

> Are we actually killing off Atlas? That seems to have happened quickly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/pittsburgh-purchasing-suite/issues/81#issuecomment-131928236
> .

## 

Patrick Hammons
@hamhandedly

**Comment by bsmithgall** [comment]
LOL

**Comment by msknee** [comment]
~\* moment of silence for Atlas *~
