### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by creade** [codeforamerica/pittsburgh-purchasing-suite#83]
Y'all got some Canadians or something over there?

**Comment by hamhands** [comment]
@creade you have something against licences?

**Comment by creade** [comment]
I've seen "Canceled" v. "Cancelled" wreak havoc like none other.

**Comment by creade** [comment]
ha ha also I would have opened the issue with the pull request but y'all have this repo closed to your fellow fellows! That's uncivil civic technology.

**Comment by hamhands** [comment]
Dammit @creade! I just pushed the same exact change to the exact same branch

**Comment by bsmithgall** [comment]
I added the fellows as collaborators @creade
