### ISSUE TITLE
Persona login/logout messages are unhelpful

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#90]

**Comment by hamhands** [comment]
Main issue is that persona doesn't state explicitly what user should login with. Is this something we can fi @bsmithgall?

**Comment by bsmithgall** [comment]
What do you mean by this? Can you be more explicit or provide a screenshot?

**Comment by hamhands** [comment]
When Stephanie logged in this morning she was confused about what to login with. When I login I see this:
<img width="285" alt="screen shot 2015-09-23 at 9 29 57 am" src="https://cloud.githubusercontent.com/assets/3640800/10046265/aec46888-61d5-11e5-95a8-67ab621580ff.png">
It has help text, so I don't know what the confusion is. I'll have her logout and see if she sees the same thing on her machine.

**Comment by hamhands** [comment]
Looks like it's an IE issue. Helper text comes up in Chrome and Firefox, but in IE it's an empty form with a blinking cursor :confused:

**Comment by bsmithgall** [comment]
@ErnieAtLYD or @phiden did either of you have any luck improving the PERSONA EXPERIENCE?

**Comment by phiden** [comment]
I did not. But maybe Ernie did?

**Comment by ErnieAtLYD** [comment]
@bsmithgall - obviously you can't touch the personal pop-up box. Maybe you can be more descriptive in `/login`?

**Comment by bsmithgall** [comment]
I mean mostly the ALERT boxes that pop up. Right now they are just like "UNAUTHORIZED" or something like that

**Comment by ErnieAtLYD** [comment]
Talking out loud: looks like the `alert` boxes come from `layout.html`. Maybe we could redirect to a hardcoded error page instead? The only problem with that is that - in theory, it's a best practice to call `navigator.id.logout()` after an error call which will naturally make the person log out. Which leaves us with "style the alert box."

**Comment by bsmithgall** [comment]
Isn't that pretty much impossible? We could have it pop open a modal or something instead of just `alert`. Maybe let's pair on a solution when you are back (or remotely?)

**Comment by phiden** [comment]
I'm happy to pair either way -- I've done some light styling on some messaging on ours, I'm just not sure they're directly persona-related.

**Comment by bsmithgall** [comment]
:+1: I'm pretty available most of this week :calendar: can you guys schedule something because I imagine you will be busier?

**Comment by msknee** [comment]
wontfixing
