### ISSUE TITLE
Signed-up users need to be re-matched against the codes they signed up for

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#98]
Here's the data:

![image](https://cloud.githubusercontent.com/assets/1957344/8641146/0c033fba-28dd-11e5-962b-6b67fdcf2fbe.png)

**Comment by hamhands** [comment]
@bsmithgall can you send me the emails when you get a chance?

**Comment by hamhands** [comment]
Codes rematched.

**Comment by bsmithgall** [comment]
:+1: :100: :confetti_ball: :fireworks: :fireworks:

**Comment by hamhands** [comment]
![giphy 10](https://cloud.githubusercontent.com/assets/3640800/9103247/d54984de-3bb0-11e5-8748-23c0fd0836be.gif)
