### ISSUE TITLE
Starring/Assignment appears to be busted

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/pittsburgh-purchasing-suite#99]

**Comment by msknee** [comment]
What happened when I attempted to assign myself a contract:

![screen shot 2015-07-12 at 9 44 29 pm](https://cloud.githubusercontent.com/assets/1178390/8641238/562cc5aa-28df-11e5-8682-8bf68e28758e.png)
![screen shot 2015-07-12 at 9 44 21 pm](https://cloud.githubusercontent.com/assets/1178390/8641239/563f43ec-28df-11e5-8729-14090e42f39c.png)

**Comment by msknee** [comment]
Attempt to star contract took me here: 

![screen shot 2015-07-12 at 9 44 38 pm](https://cloud.githubusercontent.com/assets/1178390/8641243/6923724e-28df-11e5-927c-b439d8d6cbdb.png)

**Comment by bsmithgall** [comment]
1. things are unaligned.
2. errors don't flash on conductor page
3. assignment on conductor to people who aren't me returns `NoneType object has no attribute stage_order` --> this is because there are no flows! we need to add flows and stages

**Comment by bsmithgall** [comment]
Closed by #100
